-- ============================================================
--  Plataforma Nutri — Migração 0020
--  INTELIGÊNCIA CLÍNICA — conteúdo BASE da Biblioteca de Exames (lote 1).
--
--  Origem do conteúdo: literatura primária e diretrizes (SBC, SBD, WHO,
--  Endocrine Society, ATA, KDIGO, ACG, IOM/NASEM). Escrito do zero.
--  A pós da NutMed define a ORGANIZAÇÃO (eixo/grupo), não o texto.
--
--  Cobertura do lote 1 (24 exames), ancorada nos módulos de bioquímica
--  e avaliação bioquímica da pós:
--    metabolismo do ferro · hematológico · vitaminas · minerais ·
--    glicêmico · lipídico · tireoide · hepático · inflamação
--
--  Honestidade de evidência: `ref_funcional` só é preenchida quando existe
--  base razoável. Onde a faixa funcional é contestada, `atencao` diz isso.
--  Idempotente: on conflict do slug base -> atualiza.
-- ============================================================

insert into public.ic_exames (
  nutricionista_id, nome, slug, sinonimos, unidade, eixo, grupo,
  ref_convencional, ref_funcional, interpretacao_clinica, interpretacao_funcional,
  nutrientes, sinais_alto, sinais_baixo, estrategia_alto, estrategia_baixo, atencao, referencias
) values

-- ══════════════ METABOLISMO DO FERRO ══════════════
(null, 'Ferritina', 'ferritina', '{"ferritina sérica"}', 'ng/mL',
 'Bioquímica e exames', 'Metabolismo do ferro',
 'Mulheres 15–150 · Homens 30–400 (varia por laboratório)',
 '70–100 — faixa proposta por autores da nutrição funcional para reserva "ótima"',
 'Reflete o estoque corporal de ferro e é o marcador isolado mais sensível para deficiência. A OMS adota <15 ng/mL como depleção de estoques em adultos e <70 ng/mL na vigência de infecção/inflamação. Valores baixos são específicos: ferritina baixa praticamente confirma deficiência de ferro. Valores altos são inespecíficos — podem significar sobrecarga (hemocromatose), mas muito mais frequentemente refletem inflamação, doença hepática, síndrome metabólica ou consumo alcoólico.',
 'Na abordagem funcional busca-se reserva confortável (frequentemente citada como 70–100 ng/mL) antes de considerar o ferro "adequado", especialmente diante de fadiga, queda capilar e baixa performance com ferritina dentro da faixa laboratorial mas no terço inferior. É uma faixa de conveniência clínica, não um ponto de corte diagnóstico validado.',
 '[{"nutriente":"Ferro","relacao":"Marcador direto do estoque; a reposição eleva a ferritina antes de normalizar a hemoglobina"},
   {"nutriente":"Vitamina C","relacao":"Aumenta a absorção do ferro não-heme quando consumida na mesma refeição"},
   {"nutriente":"Cálcio","relacao":"Compete com o ferro na absorção; separar laticínios e suplementos de cálcio da refeição rica em ferro"},
   {"nutriente":"Vitamina A","relacao":"Participa da mobilização do ferro hepático; deficiência associa-se a anemia que não responde só ao ferro"},
   {"nutriente":"Cobre","relacao":"Necessário à ceruloplasmina, que oxida o ferro para transporte pela transferrina"}]',
 '{"Geralmente assintomático","Fadiga e artralgia (quando há sobrecarga real)","Hiperpigmentação cutânea (sobrecarga avançada)","Hepatomegalia"}',
 '{"Fadiga desproporcional ao esforço","Queda capilar difusa","Unhas quebradiças ou coiloníquia","Intolerância ao exercício","Síndrome das pernas inquietas","Palidez de mucosas"}',
 'Antes de tratar como sobrecarga, afastar inflamação e esteatose — dosar PCR-us e saturação de transferrina. Ferritina alta com saturação normal e PCR elevada é inflamação, não excesso de ferro, e restringir ferro nesse caso não ajuda. Ferritina alta com saturação >45% pede investigação de hemocromatose. Quando associada a síndrome metabólica/esteatose, a conduta é o tratamento da doença de base: redução de gordura visceral, restrição de álcool e de açúcares livres.',
 'Priorizar fontes de ferro heme (carnes vermelhas, vísceras, aves) pela absorção superior. Combinar fontes não-heme (leguminosas, folhas escuras) com vitamina C na mesma refeição. Afastar de café, chá, laticínios e suplementos de cálcio no horário da refeição principal de ferro. Investigar a CAUSA antes de repor: fluxo menstrual aumentado, doença celíaca, gastrite atrófica, uso crônico de inibidores de bomba de prótons e sangramento digestivo são causas que a suplementação apenas mascara.',
 'Ferritina é proteína de fase aguda: sobe na inflamação e pode mascarar deficiência real. Sempre interpretar junto com PCR-us. Deficiência de ferro com ferritina "normal" é comum em obesidade e doença inflamatória — nesses casos, a saturação de transferrina e o receptor solúvel de transferrina são mais confiáveis.',
 '[{"fonte":"World Health Organization","ano":2020,"detalhe":"WHO guideline on use of ferritin concentrations to assess iron status in individuals and populations"},
   {"fonte":"World Health Organization","ano":2011,"detalhe":"Haemoglobin concentrations for the diagnosis of anaemia and assessment of severity"},
   {"fonte":"Camaschella C.","ano":2015,"detalhe":"Iron-deficiency anemia. New England Journal of Medicine"}]'),

(null, 'Saturação de transferrina', 'saturacao-transferrina', '{"IST","índice de saturação da transferrina"}', '%',
 'Bioquímica e exames', 'Metabolismo do ferro',
 '20–45%', '25–35%',
 'Percentual da transferrina ocupado por ferro; estima a oferta de ferro para a eritropoese. Abaixo de 20% indica oferta insuficiente. Acima de 45% levanta suspeita de sobrecarga e é o gatilho para investigar hemocromatose hereditária, sobretudo se persistente e acompanhada de ferritina alta.',
 'É o marcador que melhor separa deficiência real de ferritina falsamente elevada pela inflamação. Diante de ferritina normal/alta com PCR elevada e sintomas de deficiência, a saturação baixa desmascara a carência.',
 '[{"nutriente":"Ferro","relacao":"Reflete o ferro circulante disponível para a medula óssea"},
   {"nutriente":"Cobre","relacao":"Via ceruloplasmina, permite a ligação do ferro à transferrina"}]',
 '{"Costuma ser assintomático","Suspeita de hemocromatose quando >45% de forma persistente"}',
 '{"Fadiga","Baixa performance","Anemia em fase mais avançada"}',
 'Confirmar com nova coleta em jejum (a saturação tem variação diurna importante e sobe após suplemento de ferro). Persistindo >45% com ferritina alta, encaminhar para investigação de hemocromatose — é diagnóstico médico, não nutricional.',
 'Mesma estratégia da ferritina baixa: ferro heme, vitamina C junto, distanciar de cálcio/café/chá, e investigar a causa da perda.',
 'Coletar em jejum e sem suplemento de ferro nas 24h anteriores — a suplementação eleva a saturação de forma aguda e gera falso normal ou falso alto.',
 '[{"fonte":"Camaschella C.","ano":2015,"detalhe":"Iron-deficiency anemia. New England Journal of Medicine"},
   {"fonte":"European Association for the Study of the Liver (EASL)","ano":2022,"detalhe":"Clinical Practice Guidelines on haemochromatosis"}]'),

(null, 'Ferro sérico', 'ferro-serico', '{"ferro plasmático"}', 'µg/dL',
 'Bioquímica e exames', 'Metabolismo do ferro',
 '65–175 (homens) · 50–170 (mulheres)', null,
 'Mede o ferro circulante ligado à transferrina num instante. Tem valor diagnóstico limitado isoladamente: varia até 30% ao longo do dia, cai na inflamação aguda e sobe logo após a ingestão de ferro. Só faz sentido dentro do painel (com ferritina, transferrina e saturação).',
 'Pouco útil como marcador funcional isolado, justamente pela variabilidade. A abordagem funcional privilegia ferritina + saturação.',
 '[{"nutriente":"Ferro","relacao":"Fração circulante, não o estoque"}]',
 '{"Inespecífico isoladamente"}', '{"Inespecífico isoladamente"}',
 'Não conduzir por este exame isolado — reavaliar o painel completo.',
 'Não conduzir por este exame isolado — usar ferritina e saturação como guia.',
 'Nunca interpretar ferro sérico sozinho. Um valor normal não afasta deficiência e um valor baixo não a confirma.',
 '[{"fonte":"Camaschella C.","ano":2015,"detalhe":"Iron-deficiency anemia. New England Journal of Medicine"}]'),

-- ══════════════ HEMATOLÓGICO ══════════════
(null, 'Hemoglobina', 'hemoglobina', '{"Hb","hemograma"}', 'g/dL',
 'Bioquímica e exames', 'Hematológico',
 'Homens ≥13 · Mulheres não gestantes ≥12 · Gestantes ≥11 (OMS)', null,
 'Define anemia pelos pontos de corte da OMS. É um marcador TARDIO da deficiência de ferro: cai só depois que os estoques (ferritina) já se esgotaram, de modo que hemoglobina normal não afasta carência de ferro. A classificação segue o VCM: microcítica sugere ferro; macrocítica sugere B12/folato; normocítica sugere doença crônica, perda aguda ou causa mista.',
 'Na leitura funcional, a atenção volta-se ao VCM e ao RDW mesmo com hemoglobina normal — o RDW se altera antes da hemoglobina cair e sinaliza carência em instalação.',
 '[{"nutriente":"Ferro","relacao":"Componente do grupo heme; deficiência causa anemia microcítica hipocrômica"},
   {"nutriente":"Vitamina B12","relacao":"Essencial à síntese de DNA do eritroblasto; deficiência gera anemia macrocítica"},
   {"nutriente":"Folato","relacao":"Mesma via da B12; deficiência gera anemia macrocítica"},
   {"nutriente":"Vitamina B6","relacao":"Cofator da síntese do heme"},
   {"nutriente":"Cobre","relacao":"Deficiência causa anemia que não responde ao ferro"}]',
 '{"Policitemia: cefaleia, rubor facial, prurido após banho quente","Avaliar tabagismo, altitude, apneia do sono e desidratação"}',
 '{"Fadiga","Dispneia aos esforços","Palidez cutâneo-mucosa","Taquicardia","Cefaleia","Tontura"}',
 'Hemoglobina alta pede afastar hemoconcentração (desidratação), tabagismo e apneia do sono antes de qualquer conduta nutricional. Corrigir hidratação e reavaliar.',
 'Definir o tipo de anemia pelo VCM antes de suplementar. Repor ferro numa anemia por B12 não corrige e ainda atrasa o diagnóstico. Anemia é achado, não diagnóstico: a causa precisa ser encontrada.',
 'Hemoglobina normal NÃO afasta deficiência de ferro. Em gestantes há queda fisiológica por hemodiluição, com corte próprio (11 g/dL). Atletas de endurance podem ter "pseudoanemia" por expansão do volume plasmático.',
 '[{"fonte":"World Health Organization","ano":2011,"detalhe":"Haemoglobin concentrations for the diagnosis of anaemia and assessment of severity"},
   {"fonte":"World Health Organization","ano":2020,"detalhe":"WHO guideline on use of ferritin concentrations to assess iron status"}]'),

(null, 'VCM — Volume Corpuscular Médio', 'vcm', '{"volume corpuscular médio"}', 'fL',
 'Bioquímica e exames', 'Hematológico',
 '80–100', null,
 'Classifica a anemia e direciona a investigação nutricional. Microcitose (<80) aponta deficiência de ferro ou talassemia. Macrocitose (>100) aponta deficiência de B12 ou folato, hipotireoidismo, alcoolismo ou hepatopatia. É o primeiro campo a olhar num hemograma com hemoglobina baixa.',
 'Um VCM no limite inferior (80–84) com ferritina no terço inferior sugere ferro em depleção antes de a anemia se instalar — janela de intervenção precoce.',
 '[{"nutriente":"Ferro","relacao":"Deficiência reduz o VCM (microcitose)"},
   {"nutriente":"Vitamina B12","relacao":"Deficiência eleva o VCM (macrocitose)"},
   {"nutriente":"Folato","relacao":"Deficiência eleva o VCM (macrocitose)"}]',
 '{"Macrocitose: investigar B12, folato, TSH, álcool e hepatopatia"}',
 '{"Microcitose: investigar ferro e, se ferro normal, talassemia"}',
 'Dosar B12, folato e TSH. Investigar consumo alcoólico. Macrocitose com B12 e folato normais em vegetariano estrito pede dosagem de ácido metilmalônico.',
 'Dosar ferritina e saturação. Se o ferro estiver normal com microcitose persistente, considerar traço talassêmico — comum e frequentemente confundido com anemia ferropriva refratária, levando a anos de suplementação inútil.',
 'Deficiências mistas (ferro + B12) podem produzir VCM normal, com uma anulando a outra. O RDW alto denuncia a mistura.',
 '[{"fonte":"Green R, Datta Mitra A.","ano":2017,"detalhe":"Megaloblastic Anemias: Nutritional and Other Causes. Medical Clinics of North America"}]'),

(null, 'RDW', 'rdw', '{"amplitude de distribuição eritrocitária","anisocitose"}', '%',
 'Bioquímica e exames', 'Hematológico',
 '11,5–14,5', null,
 'Mede a variação de tamanho entre as hemácias. Eleva-se PRECOCEMENTE na deficiência de ferro — antes da queda do VCM e antes da queda da hemoglobina. É o achado mais subestimado do hemograma.',
 'RDW alto com hemoglobina e VCM normais é sinal de carência em instalação. É a janela para agir antes da anemia aparecer.',
 '[{"nutriente":"Ferro","relacao":"Primeiro parâmetro do hemograma a se alterar na depleção"},
   {"nutriente":"Vitamina B12","relacao":"Também eleva o RDW"},
   {"nutriente":"Folato","relacao":"Também eleva o RDW"}]',
 '{"Anisocitose: população mista de hemácias, típica de carência em instalação ou de deficiência mista"}',
 '{"Sem significado clínico quando baixo"}',
 'RDW alto isolado justifica dosar ferritina, saturação, B12 e folato mesmo com hemograma normal.',
 'Não se aplica.',
 'RDW normal não afasta deficiência. Mas RDW alto com hemograma normal é um dos sinais mais precoces disponíveis e costuma passar despercebido.',
 '[{"fonte":"Camaschella C.","ano":2015,"detalhe":"Iron-deficiency anemia. New England Journal of Medicine"}]'),

-- ══════════════ VITAMINAS ══════════════
(null, 'Vitamina D (25-OH)', 'vitamina-d', '{"25-hidroxivitamina D","calcidiol","25(OH)D"}', 'ng/mL',
 'Bioquímica e exames', 'Vitaminas',
 'Deficiência <20 · Insuficiência 20–29 · Suficiência ≥30 (Endocrine Society) — o IOM considera ≥20 suficiente para a população geral',
 '30–60 para população de risco; 40–60 frequentemente proposta em contexto funcional',
 'A 25-OH-D é a forma de estoque e o marcador correto do status (nunca a 1,25-OH, que se mantém normal ou até sobe na deficiência por estímulo do PTH). Existe divergência legítima entre sociedades: o IOM considera 20 ng/mL suficiente para saúde óssea da população geral, enquanto a Endocrine Society recomenda ≥30 para grupos de risco. No Brasil, o consenso SBEM/SBPC adota ≥20 para a população saudável e 30–60 para grupos de risco (idosos, gestantes, osteoporose, doença renal, síndromes disabsortivas).',
 'A leitura funcional trabalha com alvos mais altos (40–60) visando efeitos além do osso — imunidade, humor, sensibilidade insulínica. A evidência para desfechos extraósseos é bem mais fraca que para o osso: grandes ensaios randomizados (VITAL, D-Health) não mostraram benefício da suplementação em desfechos cardiovasculares ou de câncer em pessoas sem deficiência.',
 '[{"nutriente":"Vitamina D","relacao":"Marcador direto do estoque"},
   {"nutriente":"Cálcio","relacao":"A vitamina D regula a absorção intestinal de cálcio; repor D sem cálcio adequado limita o efeito ósseo"},
   {"nutriente":"Magnésio","relacao":"Cofator das enzimas que ativam a vitamina D; deficiência de magnésio associa-se a resposta ruim à suplementação"},
   {"nutriente":"Vitamina K2","relacao":"Direciona o cálcio para o osso; a associação é plausível mas a evidência de desfecho ainda é limitada"}]',
 '{"Intoxicação (rara, geralmente >150 ng/mL): hipercalcemia, náusea, poliúria, nefrolitíase, confusão mental"}',
 '{"Dor óssea difusa","Fraqueza muscular proximal (dificuldade em levantar da cadeira, subir escada)","Quedas de repetição no idoso","Infecções respiratórias de repetição","Humor deprimido"}',
 'Suspender suplementação e dosar cálcio sérico e PTH. Intoxicação por vitamina D é quase sempre iatrogênica — doses altas por conta própria ou prescrição em megadose sem controle. Investigar a fonte.',
 'Exposição solar regular como base. Suplementação conforme a magnitude do déficit e o grupo de risco. Garantir magnésio adequado — sem magnésio a resposta é ruim. Ingerir com refeição contendo gordura (é lipossolúvel). Reavaliar em 8–12 semanas: antes disso o platô não foi atingido e o exame não informa.',
 'Obesidade sequestra vitamina D no tecido adiposo — a mesma dose eleva menos e a necessidade costuma ser maior. Não dosar 1,25-OH para avaliar status: ela engana. Megadoses intermitentes (300.000–600.000 UI) associaram-se a AUMENTO de quedas e fraturas em idosos em ensaios randomizados — dose diária ou semanal é mais segura.',
 '[{"fonte":"Endocrine Society","ano":2011,"detalhe":"Evaluation, Treatment, and Prevention of Vitamin D Deficiency: Clinical Practice Guideline"},
   {"fonte":"Institute of Medicine (IOM/NASEM)","ano":2011,"detalhe":"Dietary Reference Intakes for Calcium and Vitamin D"},
   {"fonte":"SBEM / SBPC-ML","ano":2017,"detalhe":"Posicionamento oficial sobre intervalos de referência da vitamina D"},
   {"fonte":"Manson JE et al.","ano":2019,"detalhe":"Vitamin D Supplements and Prevention of Cancer and Cardiovascular Disease (VITAL). New England Journal of Medicine"}]'),

(null, 'Vitamina B12', 'vitamina-b12', '{"cobalamina","B12"}', 'pg/mL',
 'Bioquímica e exames', 'Vitaminas',
 '200–900 (varia por laboratório)',
 '>400 — proposta funcional; a zona 200–400 é considerada indeterminada',
 'A faixa laboratorial é reconhecidamente insensível: sintomas neurológicos ocorrem com B12 entre 200 e 400 pg/mL, e o corte de 200 deixa passar deficiência real. Diante de valor nessa zona cinzenta com clínica compatível, o ácido metilmalônico (MMA) e a homocisteína confirmam — ambos se elevam na deficiência tecidual mesmo com B12 sérica "normal".',
 'A abordagem funcional adota >400 pg/mL como alvo, sobretudo em vegetarianos, veganos, idosos, usuários crônicos de metformina ou de inibidores de bomba de prótons, e pós-bariátricos. Aqui a crítica funcional à faixa laboratorial tem respaldo: a insensibilidade do corte de 200 é reconhecida na literatura médica, não é opinião de escola.',
 '[{"nutriente":"Vitamina B12","relacao":"Marcador direto, com as ressalvas de sensibilidade"},
   {"nutriente":"Folato","relacao":"Folato alto pode mascarar a anemia da deficiência de B12 e permitir que o dano neurológico progrida silenciosamente"},
   {"nutriente":"Ferro","relacao":"Deficiência combinada é comum e pode normalizar o VCM, escondendo as duas"}]',
 '{"B12 alta sem suplementação exige atenção: pode indicar hepatopatia, doença mieloproliferativa ou neoplasia"}',
 '{"Parestesia em mãos e pés","Perda de sensibilidade vibratória e proprioceptiva","Marcha instável","Alteração de memória e concentração","Glossite (língua lisa e dolorosa)","Humor deprimido","Anemia macrocítica (achado tardio)"}',
 'B12 elevada em quem NÃO suplementa não é achado benigno — investigar fígado e hematológico. Encaminhar.',
 'Definir a causa: ingestão insuficiente (vegetariano/vegano) versus má absorção (gastrite atrófica, anemia perniciosa, pós-bariátrico, metformina, IBP). Na má absorção, dose oral alta ou parenteral — corrigir a dieta não resolve. Vegetarianos e veganos precisam de suplementação regular; não existe fonte vegetal confiável de B12 (espirulina e leveduras contêm análogos inativos que ainda competem com a B12 real).',
 'O dano neurológico da deficiência de B12 pode ser IRREVERSÍVEL se a reposição demorar, e ocorre ANTES da anemia. Não esperar o VCM subir para agir. Ácido fólico em dose alta corrige a anemia e mascara a progressão neurológica — nunca repor folato sem antes verificar a B12.',
 '[{"fonte":"Green R et al.","ano":2017,"detalhe":"Vitamin B12 deficiency. Nature Reviews Disease Primers"},
   {"fonte":"Green R, Datta Mitra A.","ano":2017,"detalhe":"Megaloblastic Anemias: Nutritional and Other Causes. Medical Clinics of North America"},
   {"fonte":"Institute of Medicine (IOM)","ano":1998,"detalhe":"Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline"}]'),

(null, 'Folato', 'folato', '{"ácido fólico","vitamina B9","folato sérico"}', 'ng/mL',
 'Bioquímica e exames', 'Vitaminas',
 '>3 (sérico) · >140 ng/mL (eritrocitário)', 'Folato eritrocitário >280 — reflete estoque, não ingestão recente',
 'O folato sérico oscila com a refeição das últimas horas e por isso informa pouco sobre estoque. O folato eritrocitário reflete os últimos 3–4 meses e é o marcador confiável. No Brasil, a fortificação obrigatória de farinhas de trigo e milho tornou a deficiência franca incomum na população geral.',
 'Interesse funcional maior em quem tem polimorfismo de MTHFR com homocisteína elevada — situação em que se propõe folato na forma metilada (5-MTHF). A relevância clínica do polimorfismo isolado, sem homocisteína alta, é fraca e não justifica conduta.',
 '[{"nutriente":"Folato","relacao":"Marcador direto"},
   {"nutriente":"Vitamina B12","relacao":"Parceiro no ciclo da metionina; repor folato sem checar B12 mascara dano neurológico"},
   {"nutriente":"Vitamina B6","relacao":"Junto com B12 e folato, regula a homocisteína"},
   {"nutriente":"Zinco","relacao":"Cofator de enzimas do metabolismo do folato"}]',
 '{"Folato sérico alto costuma refletir suplementação ou fortificação","Preocupa quando mascara deficiência de B12"}',
 '{"Anemia macrocítica","Glossite","Fadiga","Irritabilidade","Em gestantes: risco de defeito de fechamento do tubo neural"}',
 'Verificar a B12 antes de qualquer coisa. Folato alto com B12 baixa é a combinação que permite o dano neurológico progredir sem anemia para avisar.',
 'Folhas verde-escuras, leguminosas, fígado. Suplementar na gestante e na tentante — a suplementação periconcepcional reduz defeito de tubo neural e precisa começar ANTES da concepção, já que o tubo fecha por volta da 4ª semana, quando muitas mulheres ainda não sabem que estão grávidas. Sempre checar B12 junto.',
 'Folato eritrocitário é o exame que informa estoque; o sérico reflete o que a pessoa comeu ontem. Em MTHFR com homocisteína normal, não há indicação de conduta específica.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":1998,"detalhe":"Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline"},
   {"fonte":"World Health Organization","ano":2015,"detalhe":"Guideline: Optimal serum and red blood cell folate concentrations in women of reproductive age for prevention of neural tube defects"},
   {"fonte":"ANVISA","ano":2017,"detalhe":"RDC 150/2017 — fortificação de farinhas de trigo e milho com ferro e ácido fólico"}]'),

-- ══════════════ MINERAIS ══════════════
(null, 'Zinco', 'zinco', '{"zinco sérico","zinco plasmático"}', 'µg/dL',
 'Bioquímica e exames', 'Minerais',
 '70–120', '90–120 — proposta funcional, sem validação robusta',
 'O zinco sérico é um marcador ruim: representa menos de 1% do zinco corporal, cai na inflamação e após refeição, e só se altera na deficiência já avançada. Não existe bom biomarcador de zinco na prática clínica — a avaliação depende muito de ingestão, clínica e resposta terapêutica.',
 'A leitura funcional valoriza sinais clínicos (disgeusia, cicatrização lenta, queda capilar, acne, infecções de repetição) mais do que o valor sérico, o que aqui é defensável dada a fragilidade do exame.',
 '[{"nutriente":"Zinco","relacao":"Marcador direto, de sensibilidade baixa"},
   {"nutriente":"Cobre","relacao":"Competem pela absorção; zinco em dose alta prolongada causa deficiência de cobre e anemia"},
   {"nutriente":"Ferro","relacao":"Competição na absorção quando suplementados juntos em dose alta"},
   {"nutriente":"Fitatos","relacao":"Presentes em grãos e leguminosas, reduzem a absorção; demolho e fermentação atenuam"}]',
 '{"Excesso quase sempre iatrogênico","Náusea","Deficiência secundária de cobre com anemia e neuropatia"}',
 '{"Disgeusia (perda ou distorção do paladar)","Cicatrização lenta","Queda capilar","Lesões acneiformes","Infecções de repetição","Diarreia crônica","Hipogonadismo e atraso de crescimento (casos graves)"}',
 'Suspender suplementação. Zinco acima de 40 mg/dia por tempo prolongado sem controle causa deficiência de cobre — dosar cobre e ceruloplasmina. A neuropatia por deficiência de cobre induzida por zinco pode ser irreversível.',
 'Carnes, frutos do mar (ostra é a fonte mais concentrada), sementes de abóbora. Demolho e fermentação de leguminosas reduzem fitato e melhoram a absorção. Suplementar longe de ferro e cálcio em dose alta. Em vegetarianos a necessidade é maior pela carga de fitato.',
 'Coletar em jejum e longe de suplemento — o zinco sérico cai após a refeição. Zinco sérico normal NÃO afasta deficiência. Na inflamação o zinco cai por redistribuição, não por carência, e suplementar nesse cenário não corrige o exame.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":2001,"detalhe":"Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc"},
   {"fonte":"King JC et al.","ano":2015,"detalhe":"Biomarkers of Nutrition for Development (BOND) — Zinc Review. Journal of Nutrition"}]'),

(null, 'Magnésio', 'magnesio', '{"magnésio sérico","magnésio eritrocitário"}', 'mg/dL',
 'Bioquímica e exames', 'Minerais',
 'Sérico 1,7–2,2 mg/dL', 'Eritrocitário 4,2–6,8 mg/dL — reflete melhor o estoque intracelular',
 'O magnésio sérico contém cerca de 1% do magnésio corporal e é mantido às custas do osso e do músculo — permanece normal mesmo com depleção tecidual significativa. É um dos exames que mais gera falsa segurança na prática. O magnésio eritrocitário reflete melhor o compartimento intracelular, embora também tenha limitações.',
 'A crítica funcional ao magnésio sérico é bem fundamentada e reconhecida na literatura. Sintomas sugestivos (cãibra, insônia, ansiedade, constipação, enxaqueca, palpitação) com sérico normal são compatíveis com depleção — o exame não afasta.',
 '[{"nutriente":"Magnésio","relacao":"Marcador direto, com sensibilidade baixa no soro"},
   {"nutriente":"Vitamina D","relacao":"O magnésio é cofator das enzimas que ativam a vitamina D; deficiência associa-se a resposta ruim à suplementação de D"},
   {"nutriente":"Cálcio","relacao":"Antagonismo funcional na contração muscular e na condução nervosa"},
   {"nutriente":"Potássio","relacao":"A hipomagnesemia causa perda renal de potássio; hipocalemia refratária não corrige sem repor magnésio antes"}]',
 '{"Raro fora da insuficiência renal","Hipotensão","Fraqueza","Bradicardia","Depressão respiratória em casos graves"}',
 '{"Cãibras","Fasciculações e tremor","Insônia","Ansiedade e irritabilidade","Constipação","Enxaqueca","Palpitações","Hipocalemia e hipocalcemia refratárias"}',
 'Praticamente restrito à insuficiência renal ou uso de laxantes/antiácidos com magnésio. Avaliar função renal antes de qualquer suplementação.',
 'Folhas verde-escuras, sementes, oleaginosas, leguminosas, cacau. Na suplementação, a forma importa: citrato, glicinato e treonato têm boa absorção; o óxido é mal absorvido e serve mais como laxante. Uso crônico de IBP e diuréticos aumenta a perda.',
 'Magnésio sérico normal NÃO afasta deficiência — é o erro mais comum na interpretação deste exame. Hipocalemia e hipocalcemia que não corrigem costumam ser hipomagnesemia não tratada. Em insuficiência renal, suplementar só com acompanhamento médico.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":1997,"detalhe":"Dietary Reference Intakes for Calcium, Phosphorus, Magnesium, Vitamin D, and Fluoride"},
   {"fonte":"Workinger JL, Doyle RP, Bortz J.","ano":2018,"detalhe":"Challenges in the Diagnosis of Magnesium Status. Nutrients"},
   {"fonte":"Gröber U, Schmidt J, Kisters K.","ano":2015,"detalhe":"Magnesium in Prevention and Therapy. Nutrients"}]'),

-- ══════════════ GLICÊMICO ══════════════
(null, 'Glicemia de jejum', 'glicemia-jejum', '{"glicose de jejum","glicemia"}', 'mg/dL',
 'Bioquímica e exames', 'Glicêmico',
 'Normal <100 · Pré-diabetes 100–125 · Diabetes ≥126 (confirmar em 2ª coleta) — ADA/SBD',
 '75–90 — proposta funcional de faixa ótima',
 'Marcador de rastreio consolidado, mas TARDIO: a hiperglicemia de jejum aparece anos depois da resistência insulínica se instalar, quando a célula beta já perdeu boa parte da capacidade compensatória. Diagnóstico de diabetes exige confirmação em segunda coleta ou dois exames alterados na mesma amostra.',
 'A leitura funcional trabalha com alvo mais estreito e, sobretudo, com insulina de jejum e HOMA-IR — que se alteram anos antes. Aqui a crítica é procedente: esperar a glicemia de jejum subir é perder a janela mais eficaz de intervenção.',
 '[{"nutriente":"Fibras","relacao":"Solúveis reduzem a velocidade de absorção da glicose e melhoram a resposta glicêmica"},
   {"nutriente":"Magnésio","relacao":"Cofator da sinalização insulínica; deficiência associa-se a resistência à insulina"},
   {"nutriente":"Cromo","relacao":"Participa da ação insulínica; benefício da suplementação em não-deficientes é inconsistente"},
   {"nutriente":"Vitamina D","relacao":"Associação epidemiológica com sensibilidade insulínica; ensaios randomizados não confirmaram prevenção de diabetes"}]',
 '{"Poliúria","Polidipsia","Polifagia","Perda de peso inexplicada","Visão borrada","Infecções fúngicas de repetição","Cansaço"}',
 '{"Tremor","Sudorese","Taquicardia","Confusão","Irritabilidade","Fome intensa"}',
 'Confirmar com HbA1c e, se disponível, insulina de jejum. Reduzir açúcares livres e ultraprocessados, priorizar fibras e proteína nas refeições, distribuir carboidrato ao longo do dia. Perda de 5–10% do peso melhora a glicemia de forma consistente. Atividade física tem efeito independente do peso. ≥126 confirmado é diagnóstico médico — encaminhar.',
 'Hipoglicemia de jejum em quem não usa insulina ou secretagogo é achado que merece investigação médica, não ajuste de dieta.',
 'Glicemia de jejum normal NÃO afasta resistência insulínica. Para enxergar o problema cedo, olhar insulina de jejum e HOMA-IR. Jejum de 8–12h é obrigatório; jejum prolongado além disso pode elevar o valor.',
 '[{"fonte":"American Diabetes Association","ano":2024,"detalhe":"Standards of Care in Diabetes — Classification and Diagnosis"},
   {"fonte":"Sociedade Brasileira de Diabetes","ano":2023,"detalhe":"Diretriz da Sociedade Brasileira de Diabetes — diagnóstico e classificação"}]'),

(null, 'Hemoglobina glicada (HbA1c)', 'hba1c', '{"hemoglobina glicada","A1c"}', '%',
 'Bioquímica e exames', 'Glicêmico',
 'Normal <5,7 · Pré-diabetes 5,7–6,4 · Diabetes ≥6,5 — ADA/SBD',
 '<5,4 — proposta funcional',
 'Reflete a glicemia média dos últimos 2–3 meses, com peso maior para as últimas 4 semanas. Vantagem: não exige jejum e sofre pouca variação do dia a dia. É o parâmetro de acompanhamento por excelência no diabetes.',
 'O alvo funcional mais estreito busca antecipar a intervenção. Vale a ressalva de que a HbA1c também é tardia — sobe depois da resistência insulínica já instalada.',
 '[{"nutriente":"Fibras","relacao":"Melhoram o controle glicêmico de forma consistente"},
   {"nutriente":"Ferro","relacao":"A deficiência de ferro ELEVA falsamente a HbA1c — armadilha frequente"},
   {"nutriente":"Vitamina B12","relacao":"Deficiência com macrocitose pode alterar o resultado"}]',
 '{"Mesmos sintomas da hiperglicemia crônica","Risco de complicação micro e macrovascular"}',
 '{"HbA1c falsamente baixa em anemia hemolítica, sangramento recente, gestação e hemoglobinopatias"}',
 'Conduta nutricional de controle glicêmico e encaminhamento médico se ≥6,5. Reavaliar em 3 meses — antes disso o exame ainda reflete o período anterior à mudança e não mede o que você fez.',
 'HbA1c baixa com glicemia alta é discrepância que sugere interferência (hemólise, sangramento, hemoglobinopatia). Investigar antes de comemorar.',
 'Deficiência de ferro eleva falsamente a HbA1c — uma paciente ferropriva pode receber diagnóstico equivocado de pré-diabetes. Sempre cruzar com ferritina. Hemoglobinopatias (comuns na população brasileira) interferem no método. Não reavaliar antes de 3 meses.',
 '[{"fonte":"American Diabetes Association","ano":2024,"detalhe":"Standards of Care in Diabetes — Classification and Diagnosis"},
   {"fonte":"Sociedade Brasileira de Diabetes","ano":2023,"detalhe":"Diretriz da Sociedade Brasileira de Diabetes"},
   {"fonte":"English E et al.","ano":2015,"detalhe":"The effect of anaemia and abnormalities of erythrocyte indices on HbA1c analysis: a systematic review. Diabetologia"}]'),

(null, 'Insulina de jejum', 'insulina-jejum', '{"insulina basal"}', 'µUI/mL',
 'Bioquímica e exames', 'Glicêmico',
 '2–25 (faixa laboratorial ampla e pouco discriminativa)', '<8 — proposta funcional de faixa ótima',
 'A faixa laboratorial é larga demais para uso clínico: alguém com insulina 20 e glicemia normal está compensando uma resistência importante e seria classificado como "normal". Não é exame de rastreio populacional, mas é útil na avaliação individual de risco metabólico.',
 'Aqui a leitura funcional agrega valor real. A insulina de jejum se eleva ANOS antes da glicemia — é o marcador precoce de resistência insulínica, e a janela em que a intervenção nutricional tem maior impacto. Interpretar sempre junto com a glicemia, via HOMA-IR.',
 '[{"nutriente":"Fibras","relacao":"Reduzem a demanda insulínica pós-prandial"},
   {"nutriente":"Magnésio","relacao":"Cofator da sinalização insulínica"},
   {"nutriente":"Ômega-3","relacao":"Efeito anti-inflamatório com possível melhora da sensibilidade; evidência modesta"},
   {"nutriente":"Gordura visceral","relacao":"Principal determinante modificável da resistência insulínica"}]',
 '{"Acantose nigricans (escurecimento em pescoço e axilas)","Acrocórdons (pequenos pólipos cutâneos)","Gordura abdominal","Sonolência pós-prandial","Fome frequente","SOP na mulher"}',
 '{"Insulina baixa com glicemia alta sugere falência de célula beta — situação médica"}',
 'Reduzir gordura visceral é a alavanca principal. Restringir açúcares livres e ultraprocessados, aumentar fibras e proteína, treino de força (o músculo capta glicose de forma independente da insulina) e corrigir o sono — privação de sono piora a resistência de forma mensurável.',
 'Insulina baixa com hiperglicemia é achado médico (falência beta ou LADA), não nutricional. Encaminhar.',
 'Não usar como rastreio populacional — não é validado para isso e o valor isolado engana. Faz sentido no contexto individual, junto com glicemia, HOMA-IR e circunferência abdominal. Coletar em jejum de 8–12h.',
 '[{"fonte":"Matthews DR et al.","ano":1985,"detalhe":"Homeostasis model assessment: insulin resistance and beta-cell function from fasting plasma glucose and insulin concentrations in man. Diabetologia"},
   {"fonte":"Sociedade Brasileira de Diabetes","ano":2023,"detalhe":"Diretriz da Sociedade Brasileira de Diabetes"}]'),

(null, 'HOMA-IR', 'homa-ir', '{"HOMA","índice HOMA","resistência à insulina"}', 'índice',
 'Bioquímica e exames', 'Glicêmico',
 '<2,7 (corte mais citado; varia com a população estudada)', '<1,5 — proposta funcional',
 'Índice calculado: (glicemia de jejum mg/dL × insulina de jejum µUI/mL) ÷ 405. Estima resistência insulínica de forma acessível, sem clamp euglicêmico. O ponto de corte NÃO é universal — varia conforme a população, e 2,7 é o valor mais citado em estudos brasileiros.',
 'Um dos instrumentos mais úteis da leitura funcional, porque enxerga o problema na fase em que ele ainda é reversível com dieta, treino e sono. Já se altera quando glicemia e HbA1c ainda estão perfeitas.',
 '[{"nutriente":"Fibras","relacao":"Melhoram a sensibilidade insulínica"},
   {"nutriente":"Magnésio","relacao":"Deficiência associa-se a HOMA-IR mais alto"},
   {"nutriente":"Gordura visceral","relacao":"Determinante principal; a redução melhora o índice de forma consistente"},
   {"nutriente":"Ômega-3","relacao":"Efeito modesto sobre sensibilidade insulínica"}]',
 '{"Acantose nigricans","Adiposidade central","Sonolência após refeições","Dificuldade de emagrecer","SOP","Esteatose hepática"}',
 '{"Sem significado clínico estabelecido quando baixo"}',
 'Redução de gordura visceral, restrição de açúcares livres e ultraprocessados, mais fibra e proteína, treino de força e aeróbico, correção do sono. É a intervenção nutricional com melhor relação esforço/retorno na fase pré-diabética.',
 'Não se aplica.',
 'Não é válido em uso de insulina exógena nem no diabetes tipo 1. O corte varia por população — usar como tendência individual ao longo do tempo, não como um número mágico. Requer glicemia e insulina da MESMA coleta, em jejum.',
 '[{"fonte":"Matthews DR et al.","ano":1985,"detalhe":"Homeostasis model assessment: insulin resistance and beta-cell function from fasting plasma glucose and insulin concentrations in man. Diabetologia"},
   {"fonte":"Geloneze B et al.","ano":2009,"detalhe":"HOMA1-IR and HOMA2-IR indexes in identifying insulin resistance and metabolic syndrome — Brazilian Metabolic Syndrome Study (BRAMS). Arquivos Brasileiros de Endocrinologia e Metabologia"}]'),

-- ══════════════ LIPÍDICO ══════════════
(null, 'LDL-colesterol', 'ldl', '{"LDL","colesterol LDL"}', 'mg/dL',
 'Bioquímica e exames', 'Perfil lipídico',
 'Alvo por risco cardiovascular (SBC): baixo <130 · intermediário <100 · alto <70 · muito alto <50',
 null,
 'Principal alvo terapêutico na prevenção cardiovascular. Não existe "valor normal" universal: o alvo depende do risco cardiovascular global do indivíduo. A relação entre LDL e evento aterosclerótico é causal e dose-dependente, sustentada por estudos genéticos (randomização mendeliana), epidemiológicos e ensaios de intervenção — é das evidências mais sólidas da cardiologia.',
 'Parte da nutrição funcional prioriza o tamanho de partícula (LDL pequena e densa) e o LDL-P sobre o LDL-C. Há base fisiopatológica, mas a evidência de desfecho que sustenta a conduta continua sendo a do LDL-C. Não usar a discussão de subfração para relativizar um LDL-C alto em paciente de alto risco.',
 '[{"nutriente":"Gordura saturada","relacao":"A substituição por poli-insaturada reduz LDL e eventos cardiovasculares"},
   {"nutriente":"Gordura trans","relacao":"Eleva LDL e reduz HDL; sem nível seguro de consumo"},
   {"nutriente":"Fibra solúvel","relacao":"Aveia, psyllium e leguminosas reduzem LDL de forma dose-dependente"},
   {"nutriente":"Fitosteróis","relacao":"2 g/dia reduzem LDL em cerca de 8–10%"},
   {"nutriente":"Ômega-3","relacao":"Reduz triglicerídeos; efeito sobre LDL é neutro ou levemente elevador"}]',
 '{"Assintomático até o evento — este é o ponto","Xantelasma e arco corneano precoce sugerem hipercolesterolemia familiar"}',
 '{"LDL muito baixo sem tratamento pode indicar hipertireoidismo, desnutrição ou hepatopatia"}',
 'Substituir gordura saturada por mono e poli-insaturada (azeite, oleaginosas, peixes). Fibra solúvel: aveia, psyllium, leguminosas. Fitosteróis 2 g/dia. Eliminar gordura trans industrial. Reduzir peso quando indicado. LDL ≥190 sem causa secundária levanta hipercolesterolemia familiar — condição subdiagnosticada, com risco alto e indicação de rastreio familiar. Encaminhar.',
 'Investigar hipertireoidismo, desnutrição e doença hepática se muito baixo sem uso de estatina.',
 'O alvo depende do risco global, não de uma faixa única — usar o valor sem estratificar o risco leva a subtratar quem mais precisa. O cálculo de Friedewald perde validade com triglicerídeos >400 mg/dL; nesse caso pedir LDL direto. Jejum não é mais obrigatório para o perfil lipídico de rotina.',
 '[{"fonte":"Sociedade Brasileira de Cardiologia","ano":2017,"detalhe":"Atualização da Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose"},
   {"fonte":"Ference BA et al.","ano":2017,"detalhe":"Low-density lipoproteins cause atherosclerotic cardiovascular disease — Consensus Statement, European Heart Journal"},
   {"fonte":"Mach F et al. (ESC/EAS)","ano":2019,"detalhe":"Guidelines for the management of dyslipidaemias. European Heart Journal"}]'),

(null, 'Triglicerídeos', 'triglicerideos', '{"TG","triglicérides"}', 'mg/dL',
 'Bioquímica e exames', 'Perfil lipídico',
 'Desejável <150 · Limítrofe 150–199 · Alto 200–499 · Muito alto ≥500 (risco de pancreatite)',
 '<100 — proposta funcional',
 'Marcador sensível de resistência insulínica e do consumo de açúcares livres e álcool — responde rápido à mudança alimentar, o que o torna excelente para mostrar resultado ao paciente. Acima de 500 mg/dL há risco de pancreatite aguda e a conduta passa a ser urgente.',
 'A razão TG/HDL é usada na leitura funcional como estimativa indireta de resistência insulínica e de predomínio de LDL pequena e densa. Valores acima de 3 (populações brasileiras) sugerem resistência. É estimativa útil, não diagnóstico.',
 '[{"nutriente":"Açúcares livres","relacao":"Principal determinante alimentar; a frutose isolada em excesso estimula lipogênese hepática"},
   {"nutriente":"Álcool","relacao":"Elevador potente, mesmo em consumo moderado"},
   {"nutriente":"Ômega-3","relacao":"EPA/DHA em dose de 2–4 g/dia reduzem triglicerídeos em 20–30%"},
   {"nutriente":"Carboidrato refinado","relacao":"Eleva TG, sobretudo no contexto de resistência insulínica"}]',
 '{"Assintomático na maioria","≥500: risco de pancreatite","Xantomas eruptivos em valores muito altos","Frequentemente acompanha gordura visceral e esteatose"}',
 '{"TG muito baixo pode indicar desnutrição ou má absorção"}',
 'A alavanca é açúcar e álcool, não gordura. Cortar açúcares livres, refrigerante, suco e álcool. Reduzir carboidrato refinado. Ômega-3 (EPA/DHA) 2–4 g/dia em casos selecionados. Perda de peso e exercício. Responde rápido — em 4–6 semanas já se vê mudança, o que é ótimo para engajar o paciente. ≥500 é urgência: encaminhar pelo risco de pancreatite.',
 'Investigar má absorção e desnutrição se muito baixo.',
 'Exige jejum de 12h para avaliação precisa (diferente do restante do perfil lipídico). Álcool nas 72h anteriores altera bastante — orientar abstinência antes da coleta, senão o exame mede a festa do fim de semana, não a dieta.',
 '[{"fonte":"Sociedade Brasileira de Cardiologia","ano":2017,"detalhe":"Atualização da Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose"},
   {"fonte":"Skulas-Ray AC et al. (American Heart Association)","ano":2019,"detalhe":"Omega-3 Fatty Acids for the Management of Hypertriglyceridemia. Circulation"}]'),

(null, 'HDL-colesterol', 'hdl', '{"HDL","colesterol HDL"}', 'mg/dL',
 'Bioquímica e exames', 'Perfil lipídico',
 'Desejável >40 (homens) · >50 (mulheres)', null,
 'HDL baixo é marcador de risco cardiovascular, mas a relação NÃO é causal: elevar o HDL farmacologicamente não reduziu eventos em ensaios randomizados (torcetrapibe, niacina), e estudos genéticos não sustentam causalidade. Ou seja, HDL baixo sinaliza risco — não é um alvo terapêutico em si.',
 'Mais relevante como componente da razão TG/HDL na estimativa de resistência insulínica do que como alvo isolado.',
 '[{"nutriente":"Gordura monoinsaturada","relacao":"Azeite e abacate elevam modestamente o HDL"},
   {"nutriente":"Exercício aeróbico","relacao":"Um dos determinantes não alimentares mais consistentes"},
   {"nutriente":"Gordura trans","relacao":"Reduz o HDL"},
   {"nutriente":"Tabagismo","relacao":"Reduz o HDL; a cessação eleva"}]',
 '{"HDL muito alto (>90) não confere proteção adicional e em alguns estudos associou-se a maior mortalidade"}',
 '{"Marcador de risco cardiovascular","Frequentemente acompanha resistência insulínica e gordura visceral"}',
 'Não perseguir HDL alto como meta — não há evidência de benefício em elevá-lo isoladamente.',
 'Exercício aeróbico regular, cessação do tabagismo, gordura monoinsaturada, redução de peso. Mas o foco terapêutico deve permanecer no LDL e nos triglicerídeos, onde a evidência de desfecho existe.',
 'Não tratar HDL como alvo. Elevá-lo com medicamento não reduziu eventos em nenhum ensaio randomizado de grande porte. É termômetro, não alavanca.',
 '[{"fonte":"Sociedade Brasileira de Cardiologia","ano":2017,"detalhe":"Atualização da Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose"},
   {"fonte":"Voight BF et al.","ano":2012,"detalhe":"Plasma HDL cholesterol and risk of myocardial infarction: a mendelian randomisation study. The Lancet"},
   {"fonte":"HPS2-THRIVE Collaborative Group","ano":2014,"detalhe":"Effects of extended-release niacin with laropiprant in high-risk patients. New England Journal of Medicine"}]'),

-- ══════════════ TIREOIDE ══════════════
(null, 'TSH', 'tsh', '{"hormônio tireoestimulante","tirotrofina"}', 'µUI/mL',
 'Bioquímica e exames', 'Tireoide',
 '0,4–4,0 (varia por laboratório e por faixa etária)', '1,0–2,0 — proposta funcional',
 'Exame mais sensível para disfunção tireoidiana, por causa da relação log-linear com o T4 livre: pequenas variações do hormônio tireoidiano geram grandes variações do TSH. TSH elevado com T4 livre normal define hipotireoidismo subclínico. A faixa de referência sobe com a idade — um TSH de 5 aos 80 anos pode ser fisiológico e não merecer tratamento.',
 'A leitura funcional adota faixa mais estreita (1,0–2,0) e valoriza sintomas com TSH entre 2 e 4. É área de controvérsia real: a evidência de benefício em tratar TSH nessa faixa é fraca, e o ensaio TRUST não mostrou benefício sintomático de levotiroxina em idosos com hipotireoidismo subclínico. Vale investigar sintomas, mas sem transformar TSH 2,5 em doença.',
 '[{"nutriente":"Iodo","relacao":"Substrato dos hormônios tireoidianos; tanto a deficiência quanto o excesso causam disfunção"},
   {"nutriente":"Selênio","relacao":"Cofator das desiodases (T4→T3) e da glutationa peroxidase tireoidiana; pode reduzir anti-TPO na tireoidite de Hashimoto"},
   {"nutriente":"Zinco","relacao":"Participa da conversão de T4 em T3"},
   {"nutriente":"Ferro","relacao":"Cofator da tireoperoxidase; deficiência prejudica a síntese hormonal e a resposta à levotiroxina"},
   {"nutriente":"Vitamina D","relacao":"Associação com autoimunidade tireoidiana; causalidade não estabelecida"}]',
 '{"Hipotireoidismo: fadiga, ganho de peso, intolerância ao frio, constipação, pele seca, queda capilar, bradicardia, humor deprimido, edema"}',
 '{"Hipertireoidismo: perda de peso, taquicardia, tremor, insônia, ansiedade, intolerância ao calor, diarreia"}',
 'Confirmar com T4 livre e anti-TPO. Garantir iodo, selênio, zinco e ferro adequados. Hipotireoidismo subclínico em idoso frequentemente não requer tratamento — TRUST não mostrou benefício. Diagnóstico e prescrição de levotiroxina são médicos; o papel nutricional é dar substrato e cofator.',
 'TSH suprimido exige avaliação médica. Atenção ao excesso de iodo, inclusive por suplementos de alga (kelp), que podem conter doses muito altas e desencadear disfunção.',
 'Coletar pela manhã — o TSH tem ritmo circadiano com pico noturno e pode variar até 50% no dia. Biotina em dose alta (suplementos de cabelo e unha) causa INTERFERÊNCIA no ensaio e gera resultados falsos: suspender 48–72h antes. Essa é uma armadilha frequente e passa despercebida.',
 '[{"fonte":"American Thyroid Association","ano":2014,"detalhe":"Guidelines for the Treatment of Hypothyroidism. Thyroid"},
   {"fonte":"Stott DJ et al.","ano":2017,"detalhe":"Thyroid Hormone Therapy for Older Adults with Subclinical Hypothyroidism (TRUST). New England Journal of Medicine"},
   {"fonte":"Ventura M, Melo M, Carrilho F.","ano":2017,"detalhe":"Selenium and Thyroid Disease: From Pathophysiology to Treatment. International Journal of Endocrinology"}]'),

(null, 'T4 livre', 't4-livre', '{"tiroxina livre","FT4"}', 'ng/dL',
 'Bioquímica e exames', 'Tireoide',
 '0,8–1,8 (varia por laboratório)', '1,0–1,5 — proposta funcional',
 'Fração livre e biologicamente ativa da tiroxina. Usado junto do TSH para separar hipotireoidismo subclínico (TSH alto, T4L normal) de franco (TSH alto, T4L baixo). Não sofre influência das proteínas carreadoras, ao contrário do T4 total.',
 'A leitura funcional valoriza T4L no terço inferior com sintomas e observa a conversão para T3. A relevância clínica dessa leitura em pessoas sem doença tireoidiana estabelecida é limitada.',
 '[{"nutriente":"Iodo","relacao":"Substrato direto da síntese"},
   {"nutriente":"Selênio","relacao":"Cofator das desiodases que convertem T4 em T3"},
   {"nutriente":"Ferro","relacao":"Cofator da tireoperoxidase"}]',
 '{"Sintomas de hipertireoidismo"}', '{"Sintomas de hipotireoidismo"}',
 'Avaliação médica.',
 'Garantir iodo, selênio, zinco e ferro. Tratamento medicamentoso é decisão médica.',
 'Interpretar sempre junto com o TSH — isoladamente informa pouco. Biotina em dose alta interfere no ensaio: suspender 48–72h antes.',
 '[{"fonte":"American Thyroid Association","ano":2014,"detalhe":"Guidelines for the Treatment of Hypothyroidism. Thyroid"}]'),

-- ══════════════ HEPÁTICO ══════════════
(null, 'TGP / ALT', 'tgp-alt', '{"ALT","alanina aminotransferase","TGP"}', 'U/L',
 'Bioquímica e exames', 'Hepático',
 'Aproximadamente <35 (homens) · <25 (mulheres) — os cortes tradicionais (~40) são considerados altos demais',
 '<19 (mulheres) · <30 (homens) — cortes propostos por estudos de doadores saudáveis',
 'Enzima mais específica do fígado (a TGO/AST também vem de músculo, coração e hemácia). Na prática do consultório, a causa mais comum de elevação leve e persistente é a doença hepática gordurosa metabólica (esteatose), hoje chamada MASLD. Elevações leves (até 2x) pedem investigação de esteatose, álcool, medicamentos, hepatites virais e doença celíaca.',
 'A leitura funcional adota cortes mais baixos, e aqui a crítica tem respaldo na literatura médica: os limites tradicionais foram definidos em populações que incluíam pessoas com esteatose não diagnosticada, elevando artificialmente o "normal". Uma TGP de 38 numa mulher pode já ser anormal.',
 '[{"nutriente":"Açúcares livres e frutose","relacao":"Principal motor alimentar da lipogênese hepática e da esteatose"},
   {"nutriente":"Álcool","relacao":"Hepatotóxico direto e dose-dependente"},
   {"nutriente":"Vitamina E","relacao":"800 UI/dia mostrou benefício histológico na esteato-hepatite em não diabéticos (PIVENS); uso prolongado exige cautela"},
   {"nutriente":"Colina","relacao":"Necessária à exportação hepática de triglicerídeos; deficiência associa-se a esteatose"},
   {"nutriente":"Ômega-3","relacao":"Reduz gordura hepática; efeito sobre inflamação é modesto"},
   {"nutriente":"Café","relacao":"Consumo regular associa-se de forma consistente a menor progressão de fibrose hepática"}]',
 '{"Geralmente assintomático","Desconforto em hipocôndrio direito","Fadiga","Esteatose é achado de imagem, não de sintoma"}',
 '{"Sem significado clínico quando baixo"}',
 'A intervenção com melhor evidência na esteatose é a perda de peso: 5% reduz a gordura hepática, 7–10% melhora a inflamação (esteato-hepatite) e ≥10% pode melhorar a fibrose. Cortar açúcares livres, refrigerante e suco. Restringir álcool. Dieta mediterrânea tem a melhor evidência de padrão alimentar. Café regular parece proteger. Elevações >3x ou persistentes pedem investigação médica.',
 'Não se aplica.',
 'A relação TGO/TGP >2 sugere doença hepática alcoólica; <1 sugere esteatose metabólica — é uma pista simples e útil. Enzimas NORMAIS não afastam esteatose nem fibrose: parte importante dos pacientes com fibrose avançada tem transaminases normais. Exercício intenso nas 48h anteriores eleva a TGO e pode confundir.',
 '[{"fonte":"American College of Gastroenterology","ano":2017,"detalhe":"ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries"},
   {"fonte":"Prati D et al.","ano":2002,"detalhe":"Updated definitions of healthy ranges for serum alanine aminotransferase levels. Annals of Internal Medicine"},
   {"fonte":"Sanyal AJ et al.","ano":2010,"detalhe":"Pioglitazone, vitamin E, or placebo for nonalcoholic steatohepatitis (PIVENS). New England Journal of Medicine"},
   {"fonte":"Rinella ME et al. (AASLD)","ano":2023,"detalhe":"AASLD Practice Guidance on the clinical assessment and management of nonalcoholic fatty liver disease"}]'),

(null, 'GGT — Gama-GT', 'ggt', '{"gama-glutamil transferase","gama GT"}', 'U/L',
 'Bioquímica e exames', 'Hepático',
 '<38 (mulheres) · <55 (homens) — varia por laboratório', '<25 — proposta funcional',
 'Marcador sensível mas pouco específico. Eleva-se no consumo alcoólico (é o marcador mais sensível para isso), na esteatose, na colestase e no uso de vários medicamentos. Isoladamente diz pouco; em conjunto com fosfatase alcalina alta aponta colestase.',
 'Usada na leitura funcional como marcador indireto de sobrecarga hepática e de status de glutationa — a GGT participa do metabolismo da glutationa. A associação com estresse oxidativo existe na literatura epidemiológica, mas a conduta derivada disso é especulativa.',
 '[{"nutriente":"Álcool","relacao":"Determinante mais comum de elevação isolada"},
   {"nutriente":"Glutationa e precursores","relacao":"A GGT participa do ciclo do gama-glutamil; associação epidemiológica com estresse oxidativo"},
   {"nutriente":"Crucíferas","relacao":"Sustentam vias de conjugação hepática; extrapolar isso para conduta clínica vai além da evidência"},
   {"nutriente":"Café","relacao":"Consumo regular associa-se a GGT mais baixa"}]',
 '{"Geralmente assintomático","Investigar álcool, esteatose, medicamentos e colestase"}',
 '{"Sem significado clínico quando baixo"}',
 'Investigar consumo alcoólico com honestidade — a GGT costuma denunciar o que a anamnese não capta. Avaliar esteatose e medicamentos em uso. Reduzir álcool e açúcares livres, tratar a esteatose. GGT + fosfatase alcalina elevadas pedem avaliação médica de via biliar.',
 'Não se aplica.',
 'GGT isolada elevada não é diagnóstico. Muitos medicamentos comuns a elevam. Antes de construir uma narrativa de "sobrecarga tóxica", perguntar sobre álcool e conferir a lista de medicamentos — é quase sempre um dos dois.',
 '[{"fonte":"American College of Gastroenterology","ano":2017,"detalhe":"ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries"},
   {"fonte":"Whitfield JB.","ano":2001,"detalhe":"Gamma glutamyl transferase. Critical Reviews in Clinical Laboratory Sciences"}]'),

-- ══════════════ INFLAMAÇÃO ══════════════
(null, 'PCR ultrassensível', 'pcr-us', '{"PCR-us","proteína C reativa ultrassensível","hs-CRP"}', 'mg/L',
 'Bioquímica e exames', 'Inflamação',
 'Risco cardiovascular: baixo <1 · intermediário 1–3 · alto >3 · >10 sugere processo inflamatório agudo',
 '<1 — consenso entre a leitura convencional e a funcional',
 'Marcador de inflamação sistêmica de baixo grau e preditor independente de risco cardiovascular. Acima de 10 mg/L geralmente indica infecção ou inflamação aguda, e não faz sentido interpretar como risco cardiovascular — deve-se repetir depois da resolução.',
 'Muito valorizado na leitura funcional como marcador de inflamação subclínica ligada a obesidade visceral, disbiose e má qualidade alimentar. Aqui as duas leituras convergem: PCR-us <1 é alvo razoável nos dois mundos.',
 '[{"nutriente":"Ômega-3","relacao":"Reduz PCR de forma modesta e dose-dependente"},
   {"nutriente":"Fibras","relacao":"Consumo elevado associa-se a PCR mais baixa"},
   {"nutriente":"Gordura visceral","relacao":"Tecido adiposo visceral produz IL-6, que estimula a síntese hepática de PCR"},
   {"nutriente":"Ultraprocessados","relacao":"Associados a PCR mais alta em estudos observacionais"},
   {"nutriente":"Polifenóis","relacao":"Padrão alimentar rico em vegetais e azeite associa-se a menor inflamação"}]',
 '{"Inespecífico","Investigar infecção, doença autoimune, obesidade visceral, tabagismo e periodontite"}',
 '{"Sem significado clínico quando baixo"}',
 'Se >10, repetir após 2–4 semanas — provavelmente é quadro agudo e não risco cardiovascular. Entre 3 e 10 de forma persistente: reduzir gordura visceral (principal alavanca), padrão alimentar mediterrâneo, ômega-3, exercício, tratar periodontite (causa frequentemente esquecida) e cessar tabagismo.',
 'Não se aplica.',
 'Não coletar durante infecção aguda, após cirurgia ou trauma — mede o evento, não o risco basal. Exercício intenso recente eleva. É marcador inespecífico: PCR alta não indica a origem da inflamação.',
 '[{"fonte":"Ridker PM et al.","ano":2008,"detalhe":"Rosuvastatin to prevent vascular events in men and women with elevated C-reactive protein (JUPITER). New England Journal of Medicine"},
   {"fonte":"Pearson TA et al. (AHA/CDC)","ano":2003,"detalhe":"Markers of Inflammation and Cardiovascular Disease: Application to Clinical and Public Health Practice. Circulation"}]'),

(null, 'Homocisteína', 'homocisteina', '{"Hcy"}', 'µmol/L',
 'Bioquímica e exames', 'Inflamação',
 '<15 (faixa laboratorial usual)', '<8 — proposta funcional',
 'Aminoácido do ciclo da metionina. Eleva-se na deficiência de B12, folato e B6, na insuficiência renal, no hipotireoidismo e em polimorfismos de MTHFR. É marcador de risco cardiovascular em estudos observacionais — porém ensaios randomizados que a reduziram com vitaminas do complexo B NÃO reduziram eventos cardiovasculares. Ou seja: é sinal, não causa tratável pela via vitamínica.',
 'Bastante valorizada na leitura funcional como marcador de metilação e como ponte para a discussão de MTHFR. Seu valor real é ser um marcador funcional sensível de status de B12/folato/B6 — se a homocisteína está normal, essas vitaminas estão adequadas do ponto de vista funcional.',
 '[{"nutriente":"Vitamina B12","relacao":"Deficiência eleva a homocisteína; útil para confirmar deficiência com B12 sérica na zona cinzenta"},
   {"nutriente":"Folato","relacao":"Deficiência eleva a homocisteína"},
   {"nutriente":"Vitamina B6","relacao":"Cofator da via de transsulfuração"},
   {"nutriente":"Betaína e colina","relacao":"Via alternativa de remetilação da homocisteína"},
   {"nutriente":"Riboflavina (B2)","relacao":"Cofator da MTHFR; relevante sobretudo em portadores do polimorfismo"}]',
 '{"Assintomática","Marcador de risco cardiovascular e de trombose","Homocistinúria (rara, genética) cursa com valores muito altos e manifestações graves"}',
 '{"Sem significado clínico quando baixa"}',
 'Investigar e corrigir B12, folato e B6. Avaliar função renal e tireoide. Reduzir a homocisteína com vitaminas do complexo B NÃO reduziu eventos cardiovasculares nos grandes ensaios (NORVIT, HOPE-2) — corrigir a deficiência vitaminária faz sentido pelo próprio valor da vitamina, não pela promessa de proteção cardiovascular.',
 'Não se aplica.',
 'É o melhor uso clínico da homocisteína: marcador funcional de B12/folato, especialmente com B12 sérica entre 200 e 400. Não vender a redução da homocisteína como proteção cardiovascular — a evidência de intervenção não sustenta. Insuficiência renal é causa frequente e não nutricional.',
 '[{"fonte":"Bønaa KH et al.","ano":2006,"detalhe":"Homocysteine lowering and cardiovascular events after acute myocardial infarction (NORVIT). New England Journal of Medicine"},
   {"fonte":"Lonn E et al. (HOPE-2)","ano":2006,"detalhe":"Homocysteine lowering with folic acid and B vitamins in vascular disease. New England Journal of Medicine"},
   {"fonte":"Green R et al.","ano":2017,"detalhe":"Vitamin B12 deficiency. Nature Reviews Disease Primers"}]')

on conflict (slug) where (nutricionista_id is null) do update set
  sinonimos = excluded.sinonimos,
  unidade = excluded.unidade,
  eixo = excluded.eixo,
  grupo = excluded.grupo,
  ref_convencional = excluded.ref_convencional,
  ref_funcional = excluded.ref_funcional,
  interpretacao_clinica = excluded.interpretacao_clinica,
  interpretacao_funcional = excluded.interpretacao_funcional,
  nutrientes = excluded.nutrientes,
  sinais_alto = excluded.sinais_alto,
  sinais_baixo = excluded.sinais_baixo,
  estrategia_alto = excluded.estrategia_alto,
  estrategia_baixo = excluded.estrategia_baixo,
  atencao = excluded.atencao,
  referencias = excluded.referencias,
  updated_at = now();

notify pgrst, 'reload schema';
