-- ============================================================
--  Plataforma Nutri — Migração 0021
--  INTELIGÊNCIA CLÍNICA — Biblioteca de Exames, lote 2 (15 exames).
--
--  Duas motivações concretas:
--  1) Fechar as lacunas que a ponte Exames->Biblioteca expôs: marcadores
--     que os pacientes têm mas a biblioteca não cobria (Colesterol total,
--     Cortisol, Selênio, T3 livre).
--  2) Cobrir módulos da pós que ficaram sem exame no lote 1: tireoide
--     autoimune (anti-TPO), hepático completo (AST, FA), renal
--     (creatinina/TFG, ácido úrico), ósseo (cálcio, PTH), avaliação
--     nutricional (albumina) e minerais antagonistas (cobre).
--
--  Mesmo padrão do lote 1: conteúdo autoral, referência citável por item,
--  faixa funcional só onde há base razoável — e quando é contestada, o
--  campo `atencao` diz isso em vez de apresentar como fato.
-- ============================================================

insert into public.ic_exames (
  nutricionista_id, nome, slug, sinonimos, unidade, eixo, grupo,
  ref_convencional, ref_funcional, interpretacao_clinica, interpretacao_funcional,
  nutrientes, sinais_alto, sinais_baixo, estrategia_alto, estrategia_baixo, atencao, referencias
) values

-- ══════════════ PERFIL LIPÍDICO ══════════════
(null, 'Colesterol total', 'colesterol-total', '{"CT","colesterol"}', 'mg/dL',
 'Bioquímica e exames', 'Perfil lipídico',
 'Desejável <190 (a meta real depende do risco cardiovascular global)', null,
 'Soma do colesterol de todas as frações (LDL + HDL + VLDL). É o marcador mais conhecido pelo paciente e o menos útil para decidir conduta: um colesterol total de 240 pode ser HDL alto (bom) ou LDL alto (ruim), e o número sozinho não distingue. A decisão clínica se apoia no LDL e no não-HDL, estratificados pelo risco.',
 'A leitura funcional compartilha a crítica ao uso isolado do colesterol total, e com razão — a fração é que importa. Vale lembrar que colesterol é substrato de hormônios esteroides, vitamina D e sais biliares, e que valores muito baixos não são um objetivo em si.',
 '[{"nutriente":"Gordura saturada","relacao":"A substituição por poli-insaturada reduz o colesterol total e o LDL"},
   {"nutriente":"Gordura trans","relacao":"Eleva o colesterol total às custas do LDL"},
   {"nutriente":"Fibra solúvel","relacao":"Reduz a absorção intestinal de colesterol e ácidos biliares"},
   {"nutriente":"Fitosteróis","relacao":"Competem com o colesterol na absorção intestinal"},
   {"nutriente":"Colesterol alimentar","relacao":"Impacto no colesterol sérico é bem menor do que se acreditava; o ovo foi injustamente vilanizado por décadas"}]',
 '{"Assintomático","Xantelasma e arco corneano precoce sugerem hipercolesterolemia familiar"}',
 '{"Colesterol total muito baixo pode indicar hipertireoidismo, desnutrição, hepatopatia ou má absorção"}',
 'Não conduzir por este número isolado — abrir o perfil e olhar LDL e não-HDL, estratificando pelo risco. Substituir gordura saturada por insaturada, fibra solúvel, fitosteróis, eliminar trans.',
 'Investigar hipertireoidismo, má absorção e desnutrição.',
 'É o exame que mais gera conversa desnecessária no consultório. Colesterol total alto com HDL alto e LDL na meta não é problema. Sempre abrir a fração antes de assustar o paciente — ou de tranquilizá-lo.',
 '[{"fonte":"Sociedade Brasileira de Cardiologia","ano":2017,"detalhe":"Atualização da Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose"},
   {"fonte":"Mach F et al. (ESC/EAS)","ano":2019,"detalhe":"Guidelines for the management of dyslipidaemias. European Heart Journal"}]'),

(null, 'Colesterol não-HDL', 'nao-hdl', '{"não HDL","nao-HDL","colesterol não-HDL"}', 'mg/dL',
 'Bioquímica e exames', 'Perfil lipídico',
 'Alvo = LDL alvo + 30 (baixo risco <160 · intermediário <130 · alto <100 · muito alto <80)',
 null,
 'Calculado: colesterol total − HDL. Engloba TODAS as partículas aterogênicas (LDL, VLDL, IDL, remanescentes), não só o LDL. É melhor preditor de risco que o LDL isolado, especialmente quando os triglicerídeos estão altos — situação em que o LDL calculado subestima o risco real. Não exige jejum.',
 'Subutilizado na prática, embora conste nas diretrizes. Em paciente com síndrome metabólica e triglicerídeos altos — perfil comum no consultório de nutrição — é o parâmetro que conta a verdade sobre o risco.',
 '[{"nutriente":"Açúcares livres","relacao":"Elevam VLDL e remanescentes, que o não-HDL captura e o LDL não"},
   {"nutriente":"Gordura saturada","relacao":"Eleva partículas aterogênicas"},
   {"nutriente":"Fibra solúvel","relacao":"Reduz o não-HDL"}]',
 '{"Assintomático","Risco aterosclerótico aumentado, sobretudo com triglicerídeos altos"}',
 '{"Sem significado clínico estabelecido quando baixo"}',
 'Mesma conduta do LDL, com atenção extra a açúcares livres e álcool quando os triglicerídeos acompanham. É o alvo secundário mais útil na dislipidemia mista.',
 'Não se aplica.',
 'Use este parâmetro sempre que os triglicerídeos passarem de 200 — nesse cenário o LDL calculado por Friedewald engana e o não-HDL não. Não precisa de exame novo: é conta de subtração no perfil que a paciente já trouxe.',
 '[{"fonte":"Sociedade Brasileira de Cardiologia","ano":2017,"detalhe":"Atualização da Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose"},
   {"fonte":"Mach F et al. (ESC/EAS)","ano":2019,"detalhe":"Guidelines for the management of dyslipidaemias. European Heart Journal"}]'),

-- ══════════════ TIREOIDE ══════════════
(null, 'T3 livre', 't3-livre', '{"triiodotironina livre","FT3","T3"}', 'pg/mL',
 'Bioquímica e exames', 'Tireoide',
 '2,3–4,2 (varia por laboratório)', '3,0–4,0 — proposta funcional',
 'Fração livre do hormônio tireoidiano mais ativo. Não é exame de rastreio: TSH e T4 livre resolvem a grande maioria dos casos. Tem papel na suspeita de hipertireoidismo por T3 e no acompanhamento de casos selecionados. Cai na "síndrome do doente eutireoidiano" (doença aguda, jejum prolongado, restrição calórica severa), quando o corpo reduz a conversão para poupar energia — e isso NÃO é doença tireoidiana.',
 'Muito valorizado na leitura funcional pela ideia de "má conversão de T4 em T3", associada a deficiência de selênio, zinco e ferro, a cortisol alto e a restrição calórica. A fisiologia da conversão é real e os cofatores existem; o que não tem respaldo é tratar T3 no terço inferior como diagnóstico em quem tem TSH e T4 livre normais.',
 '[{"nutriente":"Selênio","relacao":"Cofator das desiodases que convertem T4 em T3 — a ligação mais direta entre nutrição e conversão"},
   {"nutriente":"Zinco","relacao":"Participa da conversão periférica"},
   {"nutriente":"Ferro","relacao":"Deficiência prejudica a síntese e a conversão"},
   {"nutriente":"Restrição calórica","relacao":"Reduz a conversão de T4 em T3 — adaptação fisiológica, não patologia"},
   {"nutriente":"Iodo","relacao":"Substrato; excesso também prejudica"}]',
 '{"Hipertireoidismo: perda de peso, taquicardia, tremor, insônia, intolerância ao calor"}',
 '{"T3 baixo com TSH normal em doença aguda ou restrição severa é adaptação, não hipotireoidismo"}',
 'Avaliação médica.',
 'Garantir selênio, zinco e ferro. Se houver restrição calórica agressiva em curso, revisar — a queda do T3 pode ser consequência da dieta, e nesse caso o alvo é a dieta, não o hormônio. Tratamento é decisão médica.',
 'T3 baixo isolado com TSH e T4L normais raramente significa doença tireoidiana. Antes de construir a narrativa de "má conversão", verificar restrição calórica, doença aguda e uso de biotina (que interfere no ensaio — suspender 48–72h antes).',
 '[{"fonte":"American Thyroid Association","ano":2014,"detalhe":"Guidelines for the Treatment of Hypothyroidism. Thyroid"},
   {"fonte":"Ventura M, Melo M, Carrilho F.","ano":2017,"detalhe":"Selenium and Thyroid Disease: From Pathophysiology to Treatment. International Journal of Endocrinology"}]'),

(null, 'Anti-TPO', 'anti-tpo', '{"anticorpo antitireoperoxidase","anti-tireoperoxidase","ATPO"}', 'UI/mL',
 'Bioquímica e exames', 'Tireoide',
 'Negativo (o corte varia por método — em geral <35)', null,
 'Marcador de autoimunidade tireoidiana. Positivo na maioria dos casos de tireoidite de Hashimoto e define a causa do hipotireoidismo. Sua presença com TSH normal indica risco aumentado de evoluir para hipotireoidismo ao longo dos anos, e justifica acompanhamento em vez de conduta imediata. O título NÃO se correlaciona com gravidade nem serve para monitorar tratamento.',
 'A leitura funcional associa a autoimunidade tireoidiana a permeabilidade intestinal, deficiência de vitamina D e selênio, e propõe retirada de glúten. Sobre o selênio há ensaios randomizados mostrando redução do título de anti-TPO — embora sem benefício clínico demonstrado. Sobre glúten, a evidência para retirada em Hashimoto SEM doença celíaca é fraca; o que é bem estabelecido é a associação entre Hashimoto e celíaca, o que justifica RASTREAR celíaca, não excluir glúten empiricamente.',
 '[{"nutriente":"Selênio","relacao":"Suplementação reduziu o título de anti-TPO em ensaios randomizados; o benefício clínico não foi demonstrado"},
   {"nutriente":"Vitamina D","relacao":"Deficiência associa-se a autoimunidade tireoidiana; causalidade não estabelecida"},
   {"nutriente":"Iodo","relacao":"Excesso pode desencadear ou piorar a tireoidite autoimune — cautela com suplementos de alga"},
   {"nutriente":"Glúten","relacao":"Retirada sem doença celíaca não tem evidência sólida; a associação com celíaca justifica rastrear, não excluir empiricamente"}]',
 '{"Positivo: risco de evoluir para hipotireoidismo","Pode cursar com fase transitória de hipertireoidismo (hashitoxicose)","Muitos pacientes seguem eutireoideos por anos"}',
 '{"Negativo não afasta Hashimoto — parte dos casos tem só anti-tireoglobulina positivo"}',
 'Anti-TPO positivo NÃO é indicação de tratamento por si só — trata-se o TSH, não o anticorpo. Acompanhar TSH periodicamente. Garantir selênio e vitamina D adequados. Evitar excesso de iodo. Rastrear doença celíaca pela associação conhecida.',
 'Não se aplica.',
 'Não repetir o anti-TPO para "acompanhar melhora" — o título não guia conduta e só gera ansiedade no paciente. Uma vez positivo, o que se monitora é o TSH. Cuidado com o excesso de iodo (kelp/alga) nesses pacientes.',
 '[{"fonte":"American Thyroid Association","ano":2014,"detalhe":"Guidelines for the Treatment of Hypothyroidism. Thyroid"},
   {"fonte":"Ventura M, Melo M, Carrilho F.","ano":2017,"detalhe":"Selenium and Thyroid Disease: From Pathophysiology to Treatment. International Journal of Endocrinology"},
   {"fonte":"Hu S, Rayman MP.","ano":2017,"detalhe":"Multiple Nutritional Factors and the Risk of Hashimoto Thyroiditis. Thyroid"}]'),

-- ══════════════ MINERAIS ══════════════
(null, 'Selênio', 'selenio', '{"selênio sérico","Se"}', 'µg/L',
 'Bioquímica e exames', 'Minerais',
 '70–150 (varia por laboratório e por região)', '100–130 — proposta funcional',
 'Cofator das desiodases (conversão de T4 em T3) e da glutationa peroxidase, uma das principais enzimas antioxidantes. O status depende muito do solo onde o alimento foi cultivado, o que torna a referência regional. No Brasil a castanha-do-pará é fonte excepcionalmente concentrada — e é justamente por isso que ela exige cuidado.',
 'Valorizado na leitura funcional pela ligação com tireoide e defesa antioxidante, o que tem base fisiológica sólida. A ressalva importante é a janela terapêutica estreita: selênio não é nutriente para suplementar "por precaução".',
 '[{"nutriente":"Selênio","relacao":"Marcador direto"},
   {"nutriente":"Iodo","relacao":"Atuam juntos na tireoide; corrigir iodo sem selênio pode piorar a tireoidite"},
   {"nutriente":"Vitamina E","relacao":"Agem de forma complementar na defesa antioxidante"},
   {"nutriente":"Castanha-do-pará","relacao":"1–2 unidades/dia suprem a necessidade; o teor varia MUITO entre lotes"}]',
 '{"Selenose: queda de cabelo, unhas quebradiças, hálito com odor de alho, náusea, irritabilidade, neuropatia"}',
 '{"Disfunção tireoidiana","Maior suscetibilidade a infecções","Fraqueza muscular","Cardiomiopatia (doença de Keshan, em deficiência severa)"}',
 'Suspender suplemento e castanha em excesso. A janela terapêutica do selênio é estreita — o limite superior tolerável para adultos é 400 µg/dia e é fácil ultrapassar comendo várias castanhas por dia achando que faz bem. Já houve casos de selenose por consumo entusiasmado de castanha.',
 'Castanha-do-pará (1–2 unidades/dia dão conta), peixes, carnes, ovos. Suplementar apenas com deficiência documentada ou indicação específica — o excesso é tóxico e a suplementação em quem já tem status adequado associou-se a maior risco de diabetes tipo 2 em alguns estudos.',
 'Nutriente com janela terapêutica estreita: pouco faz mal, muito também. O teor da castanha-do-pará varia enormemente conforme o solo de origem, então "2 castanhas por dia" não é dose confiável — é estimativa. Não suplementar sem motivo.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":2000,"detalhe":"Dietary Reference Intakes for Vitamin C, Vitamin E, Selenium, and Carotenoids"},
   {"fonte":"Rayman MP.","ano":2012,"detalhe":"Selenium and human health. The Lancet"},
   {"fonte":"Stranges S et al.","ano":2007,"detalhe":"Effects of long-term selenium supplementation on the incidence of type 2 diabetes. Annals of Internal Medicine"}]'),

(null, 'Cobre', 'cobre', '{"cobre sérico","Cu","ceruloplasmina"}', 'µg/dL',
 'Bioquímica e exames', 'Minerais',
 '70–140', null,
 'Essencial à ceruloplasmina, que oxida o ferro para transporte pela transferrina — por isso a deficiência de cobre causa anemia que NÃO responde ao ferro. Também participa da síntese de colágeno e da defesa antioxidante (superóxido dismutase). Como a ceruloplasmina é proteína de fase aguda, o cobre sérico sobe na inflamação, no uso de estrogênio e na gestação.',
 'A leitura funcional acompanha a razão zinco/cobre pela competição entre os dois. A preocupação é legítima e concreta: suplementação prolongada de zinco em dose alta é causa reconhecida de deficiência de cobre.',
 '[{"nutriente":"Zinco","relacao":"Antagonismo direto: zinco em dose alta e prolongada induz deficiência de cobre — a interação mais importante deste exame"},
   {"nutriente":"Ferro","relacao":"O cobre é necessário à mobilização do ferro; deficiência causa anemia refratária ao ferro"},
   {"nutriente":"Vitamina C","relacao":"Doses muito altas podem reduzir a absorção de cobre"}]',
 '{"Raro","Doença de Wilson (genética, acúmulo hepático e neurológico)","Investigar inflamação, estrogênio e gestação antes de considerar excesso real"}',
 '{"Anemia que não responde ao ferro","Neutropenia","Neuropatia periférica e mielopatia","Despigmentação de pele e cabelo","Fragilidade óssea"}',
 'Cobre alto quase sempre é inflamação, estrogênio ou gestação, não excesso. Investigar antes de restringir. Doença de Wilson é diagnóstico médico.',
 'Fígado, frutos do mar, castanhas, sementes, cacau. A pergunta mais importante: a pessoa está tomando zinco? Suplementação de zinco acima de 40 mg/dia por meses é a causa mais comum de deficiência de cobre na prática — e a neuropatia resultante pode ser irreversível.',
 'Sempre que prescrever zinco em dose alta por tempo prolongado, lembrar do cobre. É uma iatrogenia nutricional silenciosa: o paciente melhora do que motivou o zinco e desenvolve neuropatia meses depois, sem ninguém conectar as duas coisas.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":2001,"detalhe":"Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc"},
   {"fonte":"Myint ZW et al.","ano":2018,"detalhe":"Copper deficiency anemia. Annals of Hematology"}]'),

(null, 'Cálcio', 'calcio', '{"cálcio sérico","cálcio total","Ca"}', 'mg/dL',
 'Bioquímica e exames', 'Minerais',
 'Total 8,5–10,5 · Iônico 4,6–5,3', null,
 'O cálcio sérico é rigidamente controlado por PTH, vitamina D e calcitonina, às custas do osso — por isso NÃO reflete o estoque ósseo nem a ingestão. Uma pessoa com osteoporose grave tem cálcio sérico normal. O cálcio sérico serve para detectar distúrbios do metabolismo (hiperparatireoidismo, hipercalcemia da malignidade), não para avaliar se a paciente come cálcio suficiente.',
 'Este é um ponto em que as duas leituras concordam: o cálcio sérico não avalia status nutricional de cálcio. Avaliação de saúde óssea se faz com densitometria, ingestão alimentar, vitamina D e PTH.',
 '[{"nutriente":"Cálcio","relacao":"O sérico NÃO reflete a ingestão nem o estoque — avaliar por recordatório e densitometria"},
   {"nutriente":"Vitamina D","relacao":"Regula a absorção intestinal de cálcio"},
   {"nutriente":"Magnésio","relacao":"Hipomagnesemia causa hipocalcemia refratária — que não corrige sem repor magnésio antes"},
   {"nutriente":"Vitamina K2","relacao":"Direciona o cálcio ao osso; evidência de desfecho ainda limitada"},
   {"nutriente":"Ferro","relacao":"O cálcio compete com o ferro na absorção — separar os suplementos"}]',
 '{"Fadiga","Constipação","Náusea","Poliúria","Nefrolitíase","Confusão mental","Investigar hiperparatireoidismo e malignidade"}',
 '{"Parestesia perioral e de extremidades","Cãibras","Tetania","Sinais de Chvostek e Trousseau"}',
 'Hipercalcemia é achado médico — hiperparatireoidismo primário e malignidade são as causas principais. Suspender suplementos de cálcio e vitamina D até esclarecer. Encaminhar.',
 'Verificar magnésio ANTES de repor cálcio — hipocalcemia refratária costuma ser hipomagnesemia não tratada. Garantir vitamina D. Fontes: laticínios, vegetais verde-escuros (couve, brócolis), sardinha com espinha, tofu, gergelim.',
 'Corrigir o cálcio total pela albumina, ou pedir o cálcio iônico: albumina baixa dá cálcio total falsamente baixo sem hipocalcemia real. Fórmula usual: cálcio corrigido = cálcio total + 0,8 × (4 − albumina).',
 '[{"fonte":"Institute of Medicine (IOM)","ano":2011,"detalhe":"Dietary Reference Intakes for Calcium and Vitamin D"},
   {"fonte":"Bilezikian JP et al.","ano":2014,"detalhe":"Guidelines for the Management of Asymptomatic Primary Hyperparathyroidism. Journal of Clinical Endocrinology and Metabolism"}]'),

(null, 'PTH — Paratormônio', 'pth', '{"paratormônio","hormônio da paratireoide"}', 'pg/mL',
 'Bioquímica e exames', 'Minerais',
 '15–65 (varia por laboratório)', '<45 — proposta funcional',
 'Regula o cálcio mobilizando osso, reabsorvendo cálcio no rim e ativando a vitamina D. Sua leitura depende inteiramente do cálcio simultâneo: PTH alto com cálcio ALTO sugere hiperparatireoidismo primário (doença); PTH alto com cálcio NORMAL ou baixo sugere hiperparatireoidismo secundário — cuja causa mais comum e mais tratável é a deficiência de vitamina D.',
 'Usado na leitura funcional como marcador precoce de insuficiência de vitamina D: o PTH sobe para compensar antes de o cálcio cair. Faz sentido fisiológico e é útil — a supressão do PTH é um dos argumentos para alvos de vitamina D acima de 30 ng/mL.',
 '[{"nutriente":"Vitamina D","relacao":"Deficiência eleva o PTH; a correção o normaliza — é a causa nutricional mais comum de PTH alto"},
   {"nutriente":"Cálcio","relacao":"Ingestão baixa crônica eleva o PTH"},
   {"nutriente":"Magnésio","relacao":"Necessário à secreção e à ação do PTH; hipomagnesemia severa paradoxalmente reduz o PTH"},
   {"nutriente":"Fósforo","relacao":"Excesso (refrigerante de cola, aditivos) eleva o PTH"}]',
 '{"Perda óssea acelerada","Nefrolitíase","Com cálcio alto: investigar hiperparatireoidismo primário — é doença, encaminhar"}',
 '{"Hipocalcemia","Investigar hipomagnesemia severa e pós-operatório de tireoide"}',
 'A pergunta que separa tudo: como está o cálcio? PTH alto com cálcio ALTO é doença de paratireoide e vai para o médico. PTH alto com cálcio normal é quase sempre vitamina D baixa ou ingestão insuficiente de cálcio — e aí a conduta é sua.',
 'Investigar magnésio. Encaminhar se houver hipocalcemia sintomática.',
 'PTH nunca se interpreta sozinho — sem o cálcio da mesma coleta, o exame não informa nada. O uso mais útil na nutrição é como marcador precoce de vitamina D insuficiente, antes de o cálcio se alterar.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":2011,"detalhe":"Dietary Reference Intakes for Calcium and Vitamin D"},
   {"fonte":"Endocrine Society","ano":2011,"detalhe":"Evaluation, Treatment, and Prevention of Vitamin D Deficiency: Clinical Practice Guideline"},
   {"fonte":"Bilezikian JP et al.","ano":2014,"detalhe":"Guidelines for the Management of Asymptomatic Primary Hyperparathyroidism. Journal of Clinical Endocrinology and Metabolism"}]'),

-- ══════════════ VITAMINAS ══════════════
(null, 'Vitamina A (retinol)', 'vitamina-a', '{"retinol","retinol sérico"}', 'µg/dL',
 'Bioquímica e exames', 'Vitaminas',
 '30–65 (deficiência <20)', null,
 'O retinol sérico é mantido estável pelo fígado até que as reservas hepáticas estejam bastante depletadas — só cai na deficiência avançada, o que o torna pouco sensível. Cai também na inflamação e na deficiência de zinco (que é necessária à proteína ligadora de retinol), gerando falsa deficiência.',
 'A ligação com o ferro é o ponto mais útil na prática: a vitamina A participa da mobilização do ferro hepático, e a deficiência associa-se a anemia que não responde à suplementação isolada de ferro.',
 '[{"nutriente":"Vitamina A","relacao":"Marcador direto, de sensibilidade baixa"},
   {"nutriente":"Zinco","relacao":"Necessário à proteína ligadora de retinol; deficiência de zinco causa retinol sérico baixo sem deficiência real de vitamina A"},
   {"nutriente":"Ferro","relacao":"A vitamina A participa da mobilização do ferro hepático; deficiência causa anemia refratária ao ferro"},
   {"nutriente":"Gordura alimentar","relacao":"Necessária à absorção — é lipossolúvel"}]',
 '{"Hipervitaminose A: cefaleia, náusea, pele seca e descamativa, queda capilar, dor óssea, hepatotoxicidade","TERATOGÊNICA na gestação — risco concreto"}',
 '{"Cegueira noturna (sinal precoce e clássico)","Xeroftalmia","Hiperqueratose folicular","Infecções de repetição","Anemia refratária ao ferro"}',
 'Suspender suplemento e fígado em excesso. Atenção crítica na gestação e em tentantes: vitamina A pré-formada (retinol) em dose alta é teratogênica. Isotretinoína tem o mesmo risco. Betacaroteno não tem essa toxicidade — o corpo regula a conversão.',
 'Fígado (fonte muito concentrada), gema, laticínios integrais para retinol; vegetais alaranjados e folhas verde-escuras para betacaroteno. Garantir gordura na refeição e zinco adequado. Em anemia refratária ao ferro, lembrar da vitamina A.',
 'Retinol sérico baixo pode ser deficiência de ZINCO, não de vitamina A — dosar zinco antes de suplementar. Na gestação, o excesso de vitamina A pré-formada é teratogênico: cuidado com fígado em excesso e polivitamínicos não específicos para gestação. Betacaroteno é seguro nesse aspecto.',
 '[{"fonte":"Institute of Medicine (IOM)","ano":2001,"detalhe":"Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc"},
   {"fonte":"World Health Organization","ano":2011,"detalhe":"Serum retinol concentrations for determining the prevalence of vitamin A deficiency in populations"}]'),

-- ══════════════ HEPÁTICO ══════════════
(null, 'TGO / AST', 'tgo-ast', '{"AST","aspartato aminotransferase","TGO"}', 'U/L',
 'Bioquímica e exames', 'Hepático',
 'Aproximadamente <35 (varia por laboratório)', null,
 'Menos específica do fígado que a TGP: também vem de músculo esquelético, coração e hemácias. Por isso exercício intenso, rabdomiólise e hemólise elevam a TGO sem que haja doença hepática. Sua utilidade maior está na RAZÃO com a TGP.',
 'A razão TGO/TGP é uma pista simples e subutilizada: >2 sugere doença hepática alcoólica; <1 sugere esteatose metabólica. Ajuda a orientar a conversa sobre álcool sem depender só da anamnese.',
 '[{"nutriente":"Álcool","relacao":"Eleva desproporcionalmente a TGO — a razão TGO/TGP >2 é sugestiva"},
   {"nutriente":"Açúcares livres","relacao":"Contribuem para a esteatose, em que a razão costuma ser <1"},
   {"nutriente":"Creatina","relacao":"Suplementação e treino intenso elevam a TGO por origem muscular, sem doença hepática"}]',
 '{"Geralmente assintomático","Investigar álcool, exercício intenso recente, hemólise e doença muscular"}',
 '{"Sem significado clínico quando baixa"}',
 'Perguntar sobre exercício nas últimas 48h ANTES de investigar fígado — treino intenso é causa banal e frequente de TGO alta em quem treina. Se acompanhada de TGP alta e razão >2, a conversa é sobre álcool. Se razão <1, é esteatose: perda de peso, cortar açúcares livres, dieta mediterrânea.',
 'Não se aplica.',
 'Em atleta ou pessoa que treina pesado, TGO alta isolada com TGP normal costuma ser músculo, não fígado. Antes de assustar, perguntar o que ela fez na academia. CPK ajuda a confirmar a origem muscular.',
 '[{"fonte":"American College of Gastroenterology","ano":2017,"detalhe":"ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries"},
   {"fonte":"Botros M, Sikaris KA.","ano":2013,"detalhe":"The De Ritis Ratio: The Test of Time. Clinical Biochemist Reviews"}]'),

(null, 'Fosfatase alcalina', 'fosfatase-alcalina', '{"FA","ALP"}', 'U/L',
 'Bioquímica e exames', 'Hepático',
 '40–130 (varia por laboratório, idade e sexo)', null,
 'Vem de duas fontes principais: fígado (via biliar) e osso. Elevada com GGT alta aponta origem hepática/colestática; elevada com GGT normal aponta origem óssea — e aí entram doença de Paget, osteomalácia por deficiência severa de vitamina D e, fisiologicamente, o crescimento em adolescentes e a gestação (fonte placentária).',
 'A associação com deficiência severa de vitamina D é o achado nutricional relevante: na osteomalácia a FA sobe. Já a FA BAIXA, pouco lembrada, associa-se a deficiência de zinco e magnésio, que são cofatores da enzima.',
 '[{"nutriente":"Vitamina D","relacao":"Deficiência severa com osteomalácia eleva a FA de origem óssea"},
   {"nutriente":"Zinco","relacao":"Cofator da enzima; deficiência associa-se a FA BAIXA — pista indireta de status de zinco"},
   {"nutriente":"Magnésio","relacao":"Também cofator; deficiência pode reduzir a FA"},
   {"nutriente":"Cálcio","relacao":"Relacionado ao remodelamento ósseo que a FA reflete"}]',
 '{"Com GGT alta: colestase, obstrução biliar — encaminhar","Com GGT normal: origem óssea (Paget, osteomalácia, crescimento, gestação)"}',
 '{"FA baixa: pensar em deficiência de zinco e magnésio, hipotireoidismo e hipofosfatasia (rara)"}',
 'Pedir a GGT junto — é ela que separa fígado de osso e evita investigação na direção errada. Origem hepática com colestase é avaliação médica. Origem óssea: dosar vitamina D, cálcio e PTH.',
 'FA baixa é sinal pouco valorizado de deficiência de zinco. Vale dosar zinco e magnésio e revisar a ingestão.',
 'Nunca interpretar a FA sem a GGT — sem ela não dá para saber se o problema é fígado ou osso, e a investigação pode ir toda para o lado errado. Elevações fisiológicas ocorrem em adolescentes (crescimento) e na gestação (placenta).',
 '[{"fonte":"American College of Gastroenterology","ano":2017,"detalhe":"ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries"},
   {"fonte":"Institute of Medicine (IOM)","ano":2001,"detalhe":"Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc"}]'),

-- ══════════════ RENAL ══════════════
(null, 'Creatinina e TFG', 'creatinina-tfg', '{"creatinina","taxa de filtração glomerular","TFG","eGFR","clearance"}', 'mg/dL',
 'Bioquímica e exames', 'Renal',
 'Creatinina 0,6–1,2 (homens) · 0,5–1,1 (mulheres) · TFG ≥90 mL/min/1,73m² (KDIGO: <60 por ≥3 meses define doença renal crônica)',
 null,
 'A creatinina vem do metabolismo muscular e depende da massa muscular — por isso engana nos dois extremos: um idoso sarcopênico pode ter creatinina "normal" com função renal ruim, e um atleta musculoso pode ter creatinina alta com rins perfeitos. A TFG estimada (CKD-EPI) corrige parcialmente, mas herda a mesma limitação. Na nutrição, este é um exame de SEGURANÇA: define o que pode ou não ser prescrito.',
 'Pouco discutido na leitura funcional, e é uma lacuna séria. Função renal é o que limita suplementação de potássio, magnésio, fósforo, proteína em dose alta e vários fitoterápicos. Prescrever sem olhar o rim é o tipo de erro que machuca.',
 '[{"nutriente":"Proteína","relacao":"Ingestão alta eleva discretamente a creatinina em pessoas saudáveis sem lesar o rim; na DRC estabelecida a restrição é individualizada e conduzida com o médico"},
   {"nutriente":"Creatina","relacao":"Suplementação eleva a creatinina sérica SEM lesão renal — confunde a interpretação e assusta"},
   {"nutriente":"Potássio","relacao":"Precisa ser restrito na DRC avançada — risco de arritmia"},
   {"nutriente":"Fósforo","relacao":"Restrição necessária na DRC avançada"},
   {"nutriente":"Magnésio","relacao":"Suplementar com cautela: na insuficiência renal acumula"}]',
 '{"DRC costuma ser assintomática até estágios avançados — este é o ponto","Edema","Fadiga","Náusea","Prurido","Noctúria"}',
 '{"Creatinina baixa costuma refletir baixa massa muscular (sarcopenia, desnutrição) — achado nutricional relevante por si só"}',
 'Confirmar com nova coleta e calcular a TFG. Perguntar sobre creatina e sobre treino intenso recente — ambos elevam sem doença. TFG <60 persistente é doença renal crônica: encaminhar e revisar TODA a prescrição (potássio, fósforo, magnésio, proteína, fitoterápicos).',
 'Creatinina baixa com massa muscular reduzida é sinal de sarcopenia ou desnutrição. Avaliar ingestão proteica e força muscular — aqui o exame "normal para baixo" é a informação clínica.',
 'Antes de prescrever qualquer suplemento mineral em dose alta, olhar a função renal. Suplementação de creatina eleva a creatinina sem lesar o rim — se a paciente toma creatina, o exame não significa o que parece. Na DRC, a restrição proteica é individualizada COM o médico, nunca por conta própria.',
 '[{"fonte":"KDIGO","ano":2024,"detalhe":"KDIGO Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease"},
   {"fonte":"Levey AS et al.","ano":2009,"detalhe":"A new equation to estimate glomerular filtration rate (CKD-EPI). Annals of Internal Medicine"}]'),

(null, 'Ácido úrico', 'acido-urico', '{"urato"}', 'mg/dL',
 'Bioquímica e exames', 'Renal',
 '3,5–7,2 (homens) · 2,6–6,0 (mulheres) — meta <6,0 na gota',
 '<5,5 — proposta funcional',
 'Produto final do metabolismo das purinas. Hiperuricemia associa-se a gota, nefrolitíase, síndrome metabólica e hipertensão. Importante: a maior parte do ácido úrico é de produção ENDÓGENA — a dieta responde por parcela menor do que o senso comum sugere, e a frutose e o álcool pesam mais que a carne.',
 'A leitura funcional conecta ácido úrico a resistência insulínica e estresse oxidativo, o que tem base: a insulina reduz a excreção renal de urato, então hiperuricemia frequentemente acompanha resistência insulínica. Tratar a resistência costuma baixar o urato.',
 '[{"nutriente":"Frutose","relacao":"Aumenta a produção de ácido úrico de forma direta — refrigerante e suco pesam mais que a carne"},
   {"nutriente":"Álcool","relacao":"Cerveja é a pior (purina + álcool); reduz a excreção renal"},
   {"nutriente":"Purinas","relacao":"Vísceras e frutos do mar têm mais impacto que carne vermelha; purinas vegetais (leguminosas) NÃO aumentam risco de gota"},
   {"nutriente":"Laticínios","relacao":"Consumo associa-se a MENOR risco de gota — efeito protetor consistente"},
   {"nutriente":"Vitamina C","relacao":"Reduz modestamente o ácido úrico"},
   {"nutriente":"Café","relacao":"Consumo regular associa-se a menor risco de gota"}]',
 '{"Crise de gota: dor intensa, geralmente no hálux, de início noturno","Nefrolitíase","Tofos em casos crônicos","Frequentemente acompanha síndrome metabólica"}',
 '{"Ácido úrico muito baixo é raro e geralmente sem significado clínico"}',
 'Cortar frutose livre (refrigerante, suco) e álcool — especialmente cerveja. Estimular laticínios com baixo teor de gordura, café e vitamina C. Hidratação. Perda de peso gradual (perda rápida e jejum prolongado PIORAM: elevam o urato e podem precipitar crise). Leguminosas NÃO precisam ser restritas — a dieta de gota que proíbe feijão está desatualizada.',
 'Não se aplica.',
 'Dieta pobre em purinas de forma agressiva tem efeito modesto e péssima adesão — o alvo mais eficaz é frutose, álcool e resistência insulínica. Hiperuricemia assintomática geralmente não se trata com medicamento. Restringir leguminosas é erro comum e desnecessário.',
 '[{"fonte":"American College of Rheumatology","ano":2020,"detalhe":"Guideline for the Management of Gout"},
   {"fonte":"Choi HK et al.","ano":2004,"detalhe":"Purine-rich foods, dairy and protein intake, and the risk of gout in men. New England Journal of Medicine"},
   {"fonte":"Choi HK, Curhan G.","ano":2008,"detalhe":"Soft drinks, fructose consumption, and the risk of gout in men. BMJ"}]'),

-- ══════════════ AVALIAÇÃO NUTRICIONAL ══════════════
(null, 'Albumina', 'albumina', '{"albumina sérica"}', 'g/dL',
 'Bioquímica e exames', 'Avaliação nutricional',
 '3,5–5,2', null,
 'Historicamente usada como "marcador nutricional", o que hoje se sabe estar errado. A albumina é um marcador NEGATIVO de fase aguda: cai na inflamação, na infecção, na hepatopatia e na perda renal, independentemente do estado nutricional. Sua meia-vida longa (cerca de 20 dias) a torna insensível a mudanças recentes. As diretrizes de nutrição clínica (ASPEN/ESPEN) desaconselham explicitamente seu uso como marcador de status nutricional — mas ela sobrevive na prática por tradição.',
 'É um bom exemplo de consenso entre as duas leituras: albumina não avalia nutrição. Serve como marcador de gravidade e de inflamação, e nisso é excelente preditor de desfecho.',
 '[{"nutriente":"Proteína","relacao":"A relação é MUITO mais fraca do que se ensina; desnutrição isolada demora a baixar a albumina"},
   {"nutriente":"Inflamação","relacao":"Principal determinante da queda — mais que a ingestão"},
   {"nutriente":"Zinco","relacao":"É transportado pela albumina; albumina baixa dá zinco sérico falsamente baixo"},
   {"nutriente":"Cálcio","relacao":"Ligado à albumina; albumina baixa dá cálcio total falsamente baixo — corrigir ou pedir iônico"}]',
 '{"Albumina alta geralmente é desidratação (hemoconcentração)"}',
 '{"Edema","Ascite em casos graves","Marcador de gravidade e de inflamação","Preditor consistente de desfecho clínico ruim"}',
 'Avaliar hidratação.',
 'NÃO interpretar como desnutrição sem mais nada. Investigar inflamação (PCR-us), função hepática e perda renal (proteinúria). A avaliação nutricional se faz com anamnese alimentar, antropometria, força muscular e exame físico — não com albumina.',
 'Este é o exame que mais gera diagnóstico nutricional equivocado. Albumina baixa num paciente inflamado não significa que ele precisa de mais proteína — significa que ele está inflamado, e oferecer proteína não vai subir a albumina enquanto a inflamação estiver ativa. Lembrar também de corrigir cálcio e zinco quando a albumina está baixa.',
 '[{"fonte":"Evans DC et al. (ASPEN)","ano":2021,"detalhe":"The Use of Visceral Proteins as Nutrition Markers: An ASPEN Position Paper. Nutrition in Clinical Practice"},
   {"fonte":"Cederholm T et al. (GLIM)","ano":2019,"detalhe":"GLIM criteria for the diagnosis of malnutrition — a consensus report. Clinical Nutrition"}]'),

-- ══════════════ HORMONAL / ESTRESSE ══════════════
(null, 'Cortisol', 'cortisol', '{"cortisol sérico","cortisol matinal","cortisol salivar"}', 'µg/dL',
 'Bioquímica e exames', 'Hormonal',
 'Sérico matinal (8h) 5–25 · queda fisiológica ao longo do dia', null,
 'Hormônio com ritmo circadiano marcado: pico ao acordar, nadir à noite. Um valor isolado informa pouco sem o horário da coleta. Cortisol muito alto levanta síndrome de Cushing e muito baixo levanta insuficiência adrenal — ambos são diagnósticos médicos, raros, e exigem testes específicos (supressão com dexametasona, estímulo com ACTH), não uma dosagem avulsa.',
 'Área de maior controvérsia deste lote. A "fadiga adrenal" — ideia de que o estresse crônico esgotaria as adrenais e causaria fadiga — é popular na nutrição funcional, mas NÃO é reconhecida como entidade clínica: uma revisão sistemática de 58 estudos não encontrou evidência que a sustente. O que existe e é real: alteração do ritmo circadiano do cortisol associada a privação de sono, estresse crônico e trabalho em turnos. O cortisol salivar seriado (4 pontos) avalia o ritmo, o que é mais informativo que um ponto isolado — mas interpretar isso como "adrenais esgotadas" não se sustenta.',
 '[{"nutriente":"Sono","relacao":"Determinante mais forte do ritmo do cortisol — antes de qualquer suplemento, olhar o sono"},
   {"nutriente":"Cafeína","relacao":"Eleva o cortisol agudamente, sobretudo se consumida ao acordar ou tarde no dia"},
   {"nutriente":"Álcool","relacao":"Desorganiza o ritmo circadiano e a arquitetura do sono"},
   {"nutriente":"Restrição calórica severa","relacao":"Eleva o cortisol — a dieta agressiva pode ser a causa do que se tenta tratar"},
   {"nutriente":"Vitamina C e magnésio","relacao":"Envolvidos na resposta ao estresse; a evidência de suplementação para modular cortisol é fraca"}]',
 '{"Cushing: ganho de peso central, face em lua cheia, giba, estrias violáceas largas, fraqueza proximal, hipertensão, hiperglicemia — encaminhar"}',
 '{"Insuficiência adrenal: fadiga intensa, hipotensão postural, hiperpigmentação, avidez por sal, hipoglicemia, náusea — é emergência potencial, encaminhar"}',
 'Sinais de Cushing pedem avaliação médica com testes específicos — não se diagnostica com cortisol isolado. Do lado nutricional: sono, redução de cafeína e álcool, revisão de restrição calórica excessiva e de volume de treino.',
 'Suspeita de insuficiência adrenal é encaminhamento médico, e pode ser urgente. NÃO tratar como "fadiga adrenal" — o risco de perder uma doença de Addison real é concreto.',
 'Um cortisol isolado sem horário de coleta não interpreta nada. "Fadiga adrenal" não tem sustentação na evidência (Cadegiani & Kater revisaram 58 estudos e não acharam suporte) — e o risco prático é duplo: rotular como fadiga adrenal um paciente com insuficiência adrenal verdadeira, ou um com depressão, apneia do sono, anemia ou hipotireoidismo. Vale investigar o ritmo e, sobretudo, o sono; não vale o rótulo.',
 '[{"fonte":"Cadegiani FA, Kater CE.","ano":2016,"detalhe":"Adrenal fatigue does not exist: a systematic review. BMC Endocrine Disorders"},
   {"fonte":"Endocrine Society","ano":2008,"detalhe":"The Diagnosis of Cushing Syndrome: Clinical Practice Guideline. Journal of Clinical Endocrinology and Metabolism"},
   {"fonte":"Bornstein SR et al. (Endocrine Society)","ano":2016,"detalhe":"Diagnosis and Treatment of Primary Adrenal Insufficiency: Clinical Practice Guideline"}]')

on conflict (slug) where (nutricionista_id is null) do update set
  sinonimos = excluded.sinonimos,
  unidade = excluded.unidade,
  eixo = excluded.eixo,
  grupo = excluded.grupo,
  ref_convencional = excluded.ref_convencional,
  ref_funcional = excluded.ref_funcional,
  interpretacao_clinica = excluded.interpretacao_clinica,
  interpretacao_funcional = excluded.interpretacao_funcional,
  nutrientes = excluded.nutrientes,
  sinais_alto = excluded.sinais_alto,
  sinais_baixo = excluded.sinais_baixo,
  estrategia_alto = excluded.estrategia_alto,
  estrategia_baixo = excluded.estrategia_baixo,
  atencao = excluded.atencao,
  referencias = excluded.referencias,
  updated_at = now();

-- ------------------------------------------------------------
--  Sinônimos que a ponte Exames->Biblioteca precisa.
--  Os exames dos pacientes trazem o nome curto ("Insulina", "PCR",
--  "Vitamina D") e o casamento é exato de propósito — sem esses
--  sinônimos o marcador fica sem link.
-- ------------------------------------------------------------
update public.ic_exames set sinonimos = '{"insulina","insulina basal"}'
  where slug = 'insulina-jejum' and nutricionista_id is null;

update public.ic_exames set sinonimos = '{"PCR","PCR-us","proteína C reativa ultrassensível","proteína C reativa","hs-CRP"}'
  where slug = 'pcr-us' and nutricionista_id is null;

update public.ic_exames set sinonimos = '{"vitamina D","25-hidroxivitamina D","calcidiol","25(OH)D"}'
  where slug = 'vitamina-d' and nutricionista_id is null;

update public.ic_exames set sinonimos = '{"T4L","tiroxina livre","FT4","T4"}'
  where slug = 't4-livre' and nutricionista_id is null;

notify pgrst, 'reload schema';
