-- ============================================================
--  Plataforma Nutri — Migração 0023
--  INTELIGÊNCIA CLÍNICA — conteúdo BASE do Banco de Protocolos (lote 1).
--
--  12 protocolos, todos ancorados em módulos que EXISTEM na pós
--  (ver MAPA-POS-NUTMED.md). Conteúdo autoral, referência citável por item.
--
--  Fora deste lote, de propósito:
--  - SOP e demais temas de Saúde da Mulher: a Ana decidiu (16/07/2026) não
--    criar essa área por ora, por não ter lastro na pós. Aparece nos dados
--    de paciente e é a lacuna mais visível — candidata a revisão.
--  - Modulação intestinal (disbiose, SII): o módulo Digestório partes 2 e 3
--    ainda não foi ministrado (Avaliação II em 25/07/2026).
--
--  Todo protocolo traz `quando_encaminhar`: é o campo que marca onde termina
--  o escopo do nutricionista. Numa ferramenta de suporte à decisão, saber a
--  hora de parar vale tanto quanto saber o que fazer.
-- ============================================================

insert into public.ic_protocolos (
  nutricionista_id, nome, slug, sinonimos, eixo, grupo,
  objetivo_clinico, estrategia, nutrientes, exames_slugs, sinais_sintomas,
  materiais_apoio, referencias, quando_encaminhar, atencao
) values

-- ══════════════ 1. RESISTÊNCIA À INSULINA ══════════════
(null, 'Resistência à insulina e pré-diabetes', 'resistencia-insulina',
 '{"pré-diabetes","pre-diabetes","resistência insulínica","hiperinsulinemia","acantose"}',
 'Condições clínicas', 'Glicêmico',
 'Restaurar a sensibilidade à insulina e impedir a progressão para diabetes tipo 2, agindo na janela em que o processo ainda é reversível.',
 'A alavanca principal é a redução da gordura visceral — não o peso na balança. Perda de 5–7% do peso corporal reduziu a incidência de diabetes em 58% no Diabetes Prevention Program, resultado superior ao da metformina no mesmo estudo. Estruturar: restrição de açúcares livres e ultraprocessados; carboidrato preferencialmente integral e distribuído ao longo do dia; proteína adequada em todas as refeições (saciedade e preservação de massa magra); fibras 25–30 g/dia; gordura monoinsaturada. Treino de FORÇA é peça central e frequentemente subestimada: o músculo capta glicose por via independente da insulina (GLUT4 por contração), então ganhar músculo aumenta o destino da glicose. Aeróbico complementa. Corrigir o sono não é detalhe — privação de sono induz resistência insulínica mensurável em poucos dias, e adianta pouco ajustar a dieta de quem dorme 5 horas.',
 '[{"nutriente":"Fibras","papel":"Reduzem a resposta glicêmica e a demanda insulínica","dose":"25–30 g/dia, priorizando solúveis"},
   {"nutriente":"Magnésio","papel":"Cofator da sinalização insulínica; deficiência associa-se a HOMA-IR mais alto","dose":"Corrigir deficiência; alimentar primeiro"},
   {"nutriente":"Proteína","papel":"Saciedade e preservação de massa magra durante o déficit","dose":"1,2–1,6 g/kg/dia conforme o caso"},
   {"nutriente":"Ômega-3","papel":"Efeito anti-inflamatório; melhora modesta da sensibilidade","dose":"Peixe 2x/semana; suplementar caso a caso"},
   {"nutriente":"Cromo","papel":"Participa da ação insulínica","dose":"Benefício em não-deficientes é inconsistente — não é rotina"}]',
 '{"homa-ir","insulina-jejum","glicemia-jejum","hba1c","triglicerideos","hdl","tgp-alt"}',
 '{"Acantose nigricans (pescoço e axilas escurecidos)","Acrocórdons","Gordura abdominal","Sonolência após as refeições","Fome frequente e vontade de doce","Dificuldade de emagrecer","Esteatose hepática associada"}',
 '[{"titulo":"Prato equilibrado na prática","tipo":"orientacao","detalhe":"Metade do prato de vegetais, um quarto de proteína, um quarto de carboidrato integral"},
   {"titulo":"Higiene do sono","tipo":"habito","detalhe":"7–9h regulares; privação de sono piora a resistência insulínica de forma mensurável"},
   {"titulo":"Treino de força 2–3x/semana","tipo":"habito","detalhe":"O músculo capta glicose independente da insulina — é tratamento, não complemento"}]',
 '[{"fonte":"Knowler WC et al. (Diabetes Prevention Program)","ano":2002,"detalhe":"Reduction in the incidence of type 2 diabetes with lifestyle intervention or metformin. New England Journal of Medicine"},
   {"fonte":"Sociedade Brasileira de Diabetes","ano":2023,"detalhe":"Diretriz da Sociedade Brasileira de Diabetes"},
   {"fonte":"American Diabetes Association","ano":2024,"detalhe":"Standards of Care in Diabetes — Prevention or Delay of Diabetes"}]',
 'Glicemia de jejum ≥126 ou HbA1c ≥6,5 confirmados: encaminhar para diagnóstico e conduta médica (segue o acompanhamento nutricional). Insulina baixa com hiperglicemia sugere falência de célula beta ou LADA — encaminhar.',
 'Glicemia de jejum e HbA1c normais NÃO afastam resistência insulínica: elas se alteram tarde. Insulina de jejum e HOMA-IR enxergam anos antes — é onde a intervenção ainda muda o desfecho. Cuidado com a deficiência de ferro, que eleva falsamente a HbA1c e simula pré-diabetes.'),

-- ══════════════ 2. DIABETES TIPO 2 ══════════════
(null, 'Diabetes mellitus tipo 2', 'diabetes-tipo-2',
 '{"DM2","diabetes","diabetes tipo 2"}',
 'Condições clínicas', 'Glicêmico',
 'Apoiar o controle glicêmico, reduzir o risco de complicações micro e macrovasculares e sustentar a adesão a longo prazo.',
 'Não existe "dieta do diabético" única — as diretrizes convergem em que vários padrões alimentares funcionam (mediterrâneo, low carb, vegetariano, DASH), e o melhor é o que a paciente sustenta. Isso muda a conversa: em vez de impor um padrão, encontrar o que ela consegue manter. Estruturar: contagem ou consistência de carboidratos conforme o esquema terapêutico; priorizar carboidrato de baixo índice glicêmico e alta densidade de fibra; proteína adequada; gordura insaturada. Perda de peso é a intervenção com maior impacto: no ensaio DiRECT, remissão do DM2 foi alcançada em 46% dos participantes em 12 meses com dieta de baixa energia estruturada, e a probabilidade de remissão acompanhou a magnitude da perda. Exercício de força e aeróbico. Se a paciente usa insulina ou secretagogo (sulfonilureia), qualquer restrição de carboidrato precisa ser conversada com o médico — risco real de hipoglicemia.',
 '[{"nutriente":"Fibras","papel":"Melhoram o controle glicêmico de forma consistente","dose":"≥30 g/dia"},
   {"nutriente":"Proteína","papel":"Saciedade e preservação de massa magra","dose":"Individualizar; atenção à função renal"},
   {"nutriente":"Ômega-3","papel":"Reduz triglicerídeos","dose":"Caso a caso"},
   {"nutriente":"Magnésio","papel":"Deficiência é comum no DM2 e piora a resistência","dose":"Corrigir deficiência"},
   {"nutriente":"Vitamina B12","papel":"Metformina causa má absorção de B12 — deficiência frequente e subdiagnosticada","dose":"Monitorar anualmente em uso crônico"}]',
 '{"hba1c","glicemia-jejum","insulina-jejum","homa-ir","creatinina-tfg","ldl","triglicerideos","vitamina-b12","tgp-alt"}',
 '{"Poliúria e polidipsia","Perda de peso inexplicada","Visão borrada","Infecções fúngicas de repetição","Cicatrização lenta","Parestesia em pés (neuropatia)","Muitos casos são assintomáticos no diagnóstico"}',
 '[{"titulo":"Consistência de carboidrato entre refeições","tipo":"orientacao","detalhe":"Mais importante que eliminar: manter quantidade previsível, sobretudo em uso de insulina"},
   {"titulo":"Como agir na hipoglicemia","tipo":"orientacao","detalhe":"Regra dos 15: 15 g de carboidrato de absorção rápida, reavaliar em 15 min"},
   {"titulo":"Cuidados com os pés","tipo":"habito","detalhe":"Inspeção diária; neuropatia reduz a percepção de lesão"}]',
 '[{"fonte":"Sociedade Brasileira de Diabetes","ano":2023,"detalhe":"Diretriz da Sociedade Brasileira de Diabetes"},
   {"fonte":"American Diabetes Association","ano":2024,"detalhe":"Standards of Care in Diabetes — Facilitating Positive Health Behaviors"},
   {"fonte":"Lean MEJ et al. (DiRECT)","ano":2018,"detalhe":"Primary care-led weight management for remission of type 2 diabetes: a cluster-randomised trial. The Lancet"},
   {"fonte":"Aroda VR et al. (DPPOS)","ano":2016,"detalhe":"Long-term Metformin Use and Vitamin B12 Deficiency. Journal of Clinical Endocrinology and Metabolism"}]',
 'Hipoglicemias de repetição, HbA1c fora da meta apesar da adesão, sinais de complicação (retinopatia, nefropatia, neuropatia, pé diabético): encaminhar. Ajuste de medicação é sempre do médico.',
 'Nunca reduzir carboidrato de forma agressiva em quem usa insulina ou sulfonilureia sem alinhar com o médico — a dose fica desproporcional e a hipoglicemia é risco concreto. Em uso crônico de metformina, dosar B12: a deficiência é comum, dá neuropatia, e é facilmente confundida com neuropatia diabética.'),

-- ══════════════ 3. ESTEATOSE HEPÁTICA ══════════════
(null, 'Esteatose hepática metabólica (MASLD)', 'esteatose-hepatica',
 '{"esteatose","gordura no fígado","MASLD","NAFLD","DHGNA","fígado gorduroso"}',
 'Sistemas', 'Hepático',
 'Reduzir a gordura hepática, a inflamação e o risco de progressão para fibrose — a condição hepática mais prevalente e a mais responsiva à nutrição.',
 'A intervenção com melhor evidência é a perda de peso, e a resposta é dose-dependente: 3–5% reduz a esteatose, 7–10% melhora a esteato-hepatite (inflamação), e ≥10% pode melhorar a fibrose. Isso dá metas concretas para negociar com a paciente. Estruturar: cortar açúcares livres — refrigerante, suco, e sobretudo frutose industrial, que é o motor da lipogênese hepática de novo; restringir álcool (mesmo "social" pesa aqui); dieta mediterrânea é o padrão com melhor evidência; reduzir ultraprocessados. Café regular associa-se de forma consistente a menor progressão de fibrose — é das poucas recomendações "prazerosas" com respaldo. Exercício reduz gordura hepática mesmo SEM perda de peso, o que é um argumento útil para quem estaciona na balança e desanima.',
 '[{"nutriente":"Açúcares livres e frutose","papel":"Motor da lipogênese hepática — o alvo alimentar número um","dose":"Reduzir ao mínimo; eliminar bebidas açucaradas"},
   {"nutriente":"Ômega-3","papel":"Reduz gordura hepática; efeito modesto sobre inflamação","dose":"Peixe 2x/semana; suplementação caso a caso"},
   {"nutriente":"Vitamina E","papel":"800 UI/dia melhorou histologia na esteato-hepatite em NÃO diabéticos (PIVENS)","dose":"Uso prolongado exige cautela e decisão compartilhada com o médico"},
   {"nutriente":"Café","papel":"Consumo regular associa-se a menor progressão de fibrose","dose":"2–3 xícaras/dia, sem açúcar"},
   {"nutriente":"Colina","papel":"Necessária à exportação hepática de triglicerídeos","dose":"Garantir ingestão (ovo, fígado)"}]',
 '{"tgp-alt","tgo-ast","ggt","homa-ir","insulina-jejum","triglicerideos","ferritina","hba1c"}',
 '{"Geralmente assintomática — este é o problema","Desconforto em hipocôndrio direito","Fadiga","Gordura visceral","Quase sempre acompanha resistência insulínica"}',
 '[{"titulo":"Adeus às calorias líquidas","tipo":"orientacao","detalhe":"Refrigerante e suco são o alvo mais rentável; a frutose líquida vai direto para a lipogênese"},
   {"titulo":"Dieta mediterrânea na prática","tipo":"orientacao","detalhe":"Azeite, peixe, leguminosas, vegetais, oleaginosas; padrão com melhor evidência"},
   {"titulo":"Exercício funciona mesmo sem emagrecer","tipo":"habito","detalhe":"Reduz gordura hepática de forma independente do peso — usar para sustentar a adesão"}]',
 '[{"fonte":"Rinella ME et al. (AASLD)","ano":2023,"detalhe":"AASLD Practice Guidance on the clinical assessment and management of nonalcoholic fatty liver disease"},
   {"fonte":"European Association for the Study of the Liver (EASL)","ano":2024,"detalhe":"EASL-EASD-EASO Clinical Practice Guidelines on the management of metabolic dysfunction-associated steatotic liver disease"},
   {"fonte":"Sanyal AJ et al.","ano":2010,"detalhe":"Pioglitazone, vitamin E, or placebo for nonalcoholic steatohepatitis (PIVENS). New England Journal of Medicine"},
   {"fonte":"Vilar-Gomez E et al.","ano":2015,"detalhe":"Weight Loss Through Lifestyle Modification Significantly Reduces Features of Nonalcoholic Steatohepatitis. Gastroenterology"}]',
 'Sinais de doença hepática avançada (ascite, icterícia, encefalopatia, plaquetopenia), transaminases >3x o limite, ou suspeita de fibrose avançada: encaminhar para hepatologista. Estratificação de fibrose (FIB-4, elastografia) é conduta médica.',
 'Transaminases NORMAIS não afastam esteatose nem fibrose — parte relevante dos pacientes com fibrose avançada tem enzimas normais. Perda de peso rápida demais (>1,5 kg/semana) pode PIORAR a inflamação hepática: a perda precisa ser gradual. Ferritina alta aqui costuma ser inflamação/esteatose, não sobrecarga de ferro.'),

-- ══════════════ 4. ANEMIA FERROPRIVA ══════════════
(null, 'Anemia ferropriva', 'anemia-ferropriva',
 '{"anemia","deficiência de ferro","ferropenia","falta de ferro"}',
 'Bioquímica e exames', 'Metabolismo do ferro',
 'Corrigir a deficiência de ferro e — mais importante — identificar e tratar a CAUSA da perda, que a suplementação apenas mascara.',
 'A pergunta central não é "quanto ferro repor", é "por que ela está perdendo ferro". Suplementar sem investigar é o erro clássico: resolve o exame e deixa a causa correr. Investigar sempre: fluxo menstrual aumentado (causa mais comum na mulher em idade fértil), sangramento digestivo (causa mais comum no homem e na pós-menopausa — e que exige investigação médica), doença celíaca, gastrite atrófica, uso crônico de inibidor de bomba de prótons, cirurgia bariátrica, doação frequente de sangue. Estratégia alimentar: priorizar ferro heme (carnes, vísceras, aves), que tem absorção muito superior; combinar fontes não-heme (leguminosas, folhas escuras) com vitamina C na mesma refeição; afastar café, chá, laticínios e suplementos de cálcio do horário da refeição principal de ferro. Na suplementação, a evidência mudou: doses menores em DIAS ALTERNADOS absorvem melhor que doses altas diárias, porque a hepcidina sobe por 24h após cada dose e bloqueia a absorção seguinte — e ainda causam menos efeito gastrointestinal, o que melhora a adesão.',
 '[{"nutriente":"Ferro","papel":"Reposição do estoque","dose":"Dias alternados absorve melhor que diário (hepcidina); dose e forma conforme o caso"},
   {"nutriente":"Vitamina C","papel":"Aumenta a absorção do ferro não-heme","dose":"Fonte na mesma refeição"},
   {"nutriente":"Vitamina A","papel":"Mobiliza o ferro hepático; deficiência causa anemia refratária ao ferro","dose":"Garantir adequação"},
   {"nutriente":"Cobre","papel":"Necessário à ceruloplasmina; deficiência causa anemia que não responde ao ferro","dose":"Investigar se não houver resposta"},
   {"nutriente":"Cálcio","papel":"Compete com o ferro","dose":"Separar dos suplementos e laticínios"}]',
 '{"ferritina","saturacao-transferrina","ferro-serico","hemoglobina","vcm","rdw","pcr-us","vitamina-a"}',
 '{"Fadiga desproporcional ao esforço","Queda capilar difusa","Unhas quebradiças ou coiloníquia","Palidez de mucosas","Intolerância ao exercício","Síndrome das pernas inquietas","Pica (desejo de gelo, terra)","Taquicardia e dispneia aos esforços"}',
 '[{"titulo":"Como tomar o ferro","tipo":"orientacao","detalhe":"Em jejum ou com vitamina C; longe de café, chá, leite e cálcio; dias alternados absorve melhor"},
   {"titulo":"Ferro heme x não-heme","tipo":"orientacao","detalhe":"Carnes têm absorção muito superior; vegetal precisa de vitamina C junto"},
   {"titulo":"Reavaliar em 8–12 semanas","tipo":"orientacao","detalhe":"A ferritina sobe antes da hemoglobina; antes disso o exame não informa"}]',
 '[{"fonte":"Camaschella C.","ano":2015,"detalhe":"Iron-deficiency anemia. New England Journal of Medicine"},
   {"fonte":"World Health Organization","ano":2020,"detalhe":"WHO guideline on use of ferritin concentrations to assess iron status"},
   {"fonte":"Stoffel NU et al.","ano":2017,"detalhe":"Iron absorption from oral iron supplements given on consecutive versus alternate days. The Lancet Haematology"},
   {"fonte":"Moretti D et al.","ano":2015,"detalhe":"Oral iron supplements increase hepcidin and decrease iron absorption from daily or twice-daily doses. Blood"}]',
 'Anemia em homem ou em mulher na pós-menopausa exige investigação de sangramento digestivo — encaminhar, é prioridade. Anemia severa (Hb <8), sintomática, ou que não responde à reposição adequada em 3 meses: encaminhar. Suspeita de celíaca ou doença inflamatória intestinal: encaminhar.',
 'Ferritina é proteína de fase aguda: sobe na inflamação e mascara deficiência real — sempre ler junto com PCR-us. Anemia não é diagnóstico, é achado: sem investigar a causa, a suplementação vira paliativo. Microcitose que não responde ao ferro, com ferro normal, levanta traço talassêmico — comum no Brasil e frequentemente tratado por anos como ferropriva refratária.'),

-- ══════════════ 5. HIPOTIREOIDISMO E HASHIMOTO ══════════════
(null, 'Hipotireoidismo e tireoidite de Hashimoto', 'hipotireoidismo-hashimoto',
 '{"hipotireoidismo","Hashimoto","tireoidite","tireoide lenta"}',
 'Sistemas', 'Tireoide',
 'Oferecer substrato e cofatores para a função tireoidiana, apoiar a eficácia do tratamento medicamentoso e evitar as interferências alimentares que o sabotam.',
 'O papel nutricional aqui é de suporte, não de substituição: o tratamento do hipotireoidismo é a levotiroxina, e isso é decisão médica. O que a nutrição entrega e que faz diferença real: garantir iodo, selênio, zinco e ferro (todos cofatores da síntese ou da conversão); orientar corretamente a tomada da levotiroxina — em jejum, 30–60 min antes do café, e longe de cálcio, ferro, café e soja, que reduzem a absorção e são causa frequente de "hormônio que não funciona"; e corrigir deficiência de ferro, que prejudica a resposta ao tratamento. Sobre glúten: a retirada em Hashimoto SEM doença celíaca não tem evidência sólida. O que é bem estabelecido é a associação entre Hashimoto e celíaca — o que justifica RASTREAR celíaca, não excluir glúten empiricamente. Sobre crucíferas: o efeito bociogênico exige consumo cru e em quantidade irreal; cozidas e em porções normais, não há motivo para restringir — e restringir empobrece a dieta sem ganho.',
 '[{"nutriente":"Iodo","papel":"Substrato da síntese hormonal","dose":"Adequação, não excesso — o excesso pode desencadear ou piorar a tireoidite"},
   {"nutriente":"Selênio","papel":"Cofator das desiodases; reduziu anti-TPO em ensaios randomizados","dose":"Castanha-do-pará 1–2/dia; janela terapêutica estreita, não exagerar"},
   {"nutriente":"Zinco","papel":"Participa da conversão de T4 em T3","dose":"Garantir adequação"},
   {"nutriente":"Ferro","papel":"Cofator da tireoperoxidase; deficiência prejudica a resposta à levotiroxina","dose":"Corrigir deficiência — impacta o tratamento"},
   {"nutriente":"Vitamina D","papel":"Associação com autoimunidade; causalidade não estabelecida","dose":"Corrigir deficiência"}]',
 '{"tsh","t4-livre","t3-livre","anti-tpo","ferritina","selenio","vitamina-d","zinco","colesterol-total"}',
 '{"Fadiga","Ganho de peso","Intolerância ao frio","Constipação","Pele seca e queda capilar","Bradicardia","Humor deprimido","Edema","Irregularidade menstrual","Colesterol total elevado"}',
 '[{"titulo":"Como tomar a levotiroxina","tipo":"orientacao","detalhe":"Jejum, 30–60 min antes do café, longe de cálcio, ferro, café e soja — erro comum que faz o hormônio parecer ineficaz"},
   {"titulo":"Crucíferas podem, sim","tipo":"orientacao","detalhe":"O efeito bociogênico exige consumo cru e irreal; cozidas e em porção normal não há motivo para restringir"},
   {"titulo":"Cuidado com suplemento de alga","tipo":"orientacao","detalhe":"Kelp pode ter doses muito altas de iodo e desencadear disfunção"}]',
 '[{"fonte":"American Thyroid Association","ano":2014,"detalhe":"Guidelines for the Treatment of Hypothyroidism. Thyroid"},
   {"fonte":"Stott DJ et al. (TRUST)","ano":2017,"detalhe":"Thyroid Hormone Therapy for Older Adults with Subclinical Hypothyroidism. New England Journal of Medicine"},
   {"fonte":"Hu S, Rayman MP.","ano":2017,"detalhe":"Multiple Nutritional Factors and the Risk of Hashimoto Thyroiditis. Thyroid"},
   {"fonte":"Ventura M, Melo M, Carrilho F.","ano":2017,"detalhe":"Selenium and Thyroid Disease. International Journal of Endocrinology"}]',
 'Diagnóstico e ajuste de levotiroxina são médicos. TSH suprimido, nódulo palpável, crescimento cervical rápido ou sintomas compressivos: encaminhar. Hipotireoidismo subclínico em idoso frequentemente NÃO requer tratamento — o ensaio TRUST não mostrou benefício sintomático.',
 'Anti-TPO positivo não é indicação de tratamento por si só, e repetir o título não guia conduta — trata-se o TSH, não o anticorpo. Biotina (suplementos de cabelo e unha) interfere no ensaio e falseia TSH, T4 e T3: suspender 48–72h antes da coleta. Essa armadilha é frequente e passa despercebida. Excesso de iodo pode piorar a tireoidite autoimune.'),

-- ══════════════ 6. DISLIPIDEMIA ══════════════
(null, 'Dislipidemia', 'dislipidemia',
 '{"colesterol alto","triglicerídeos altos","hipercolesterolemia","LDL alto"}',
 'Sistemas', 'Cardiovascular',
 'Reduzir o risco cardiovascular pela redução das partículas aterogênicas, com metas definidas pelo risco global — não por uma faixa única.',
 'O primeiro passo não é dietético: é estratificar o risco. O mesmo LDL de 140 é aceitável numa jovem sem fator de risco e inaceitável num diabético com doença aterosclerótica — sem estratificar, subtrata-se quem mais precisa. Sobre LDL: substituir gordura saturada por poli e monoinsaturada (a substituição é o que reduz eventos — apenas cortar saturada e repor com carboidrato refinado não ajuda); fibra solúvel (aveia, psyllium, leguminosas) de forma dose-dependente; fitosteróis 2 g/dia reduzem LDL em 8–10%; eliminar gordura trans industrial. Sobre triglicerídeos, a alavanca é outra e isso confunde muita gente: açúcares livres e álcool pesam muito mais que gordura. Ômega-3 (EPA/DHA) 2–4 g/dia reduz triglicerídeos em 20–30% em casos selecionados. HDL não é alvo terapêutico — elevá-lo farmacologicamente não reduziu eventos em nenhum ensaio de grande porte.',
 '[{"nutriente":"Gordura saturada","papel":"A SUBSTITUIÇÃO por insaturada reduz LDL e eventos; só cortar não basta","dose":"<7–10% do valor energético, substituindo por insaturada"},
   {"nutriente":"Fibra solúvel","papel":"Reduz LDL de forma dose-dependente","dose":"5–10 g/dia de solúvel (aveia, psyllium, leguminosas)"},
   {"nutriente":"Fitosteróis","papel":"Competem com o colesterol na absorção","dose":"2 g/dia reduzem LDL 8–10%"},
   {"nutriente":"Ômega-3 (EPA/DHA)","papel":"Reduz triglicerídeos; efeito sobre LDL é neutro ou levemente elevador","dose":"2–4 g/dia em hipertrigliceridemia"},
   {"nutriente":"Gordura trans","papel":"Eleva LDL e reduz HDL","dose":"Sem nível seguro — eliminar"},
   {"nutriente":"Álcool","papel":"Elevador potente de triglicerídeos","dose":"Restringir, sobretudo com TG >200"}]',
 '{"ldl","hdl","triglicerideos","colesterol-total","nao-hdl","glicemia-jejum","tsh","tgp-alt"}',
 '{"Assintomática até o evento cardiovascular — este é o ponto","Xantelasma","Arco corneano precoce (<45 anos)","Xantomas eruptivos na hipertrigliceridemia severa"}',
 '[{"titulo":"Trocar, não só cortar","tipo":"orientacao","detalhe":"Substituir manteiga/banha por azeite e oleaginosas; cortar saturada e repor com carboidrato refinado não reduz risco"},
   {"titulo":"Aveia e psyllium no dia a dia","tipo":"orientacao","detalhe":"Fibra solúvel com efeito dose-dependente sobre o LDL"},
   {"titulo":"Triglicerídeo é açúcar e álcool","tipo":"orientacao","detalhe":"A alavanca é diferente da do colesterol — responde em 4–6 semanas, ótimo para engajar"}]',
 '[{"fonte":"Sociedade Brasileira de Cardiologia","ano":2017,"detalhe":"Atualização da Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose"},
   {"fonte":"Mach F et al. (ESC/EAS)","ano":2019,"detalhe":"Guidelines for the management of dyslipidaemias. European Heart Journal"},
   {"fonte":"Ference BA et al.","ano":2017,"detalhe":"Low-density lipoproteins cause atherosclerotic cardiovascular disease. European Heart Journal"},
   {"fonte":"Skulas-Ray AC et al. (AHA)","ano":2019,"detalhe":"Omega-3 Fatty Acids for the Management of Hypertriglyceridemia. Circulation"}]',
 'LDL ≥190 sem causa secundária levanta hipercolesterolemia familiar — condição subdiagnosticada, de alto risco, com indicação de rastreio da família: encaminhar. Triglicerídeos ≥500: risco de pancreatite, conduta urgente. Doença aterosclerótica estabelecida ou risco alto: a indicação de estatina é médica, e a nutrição não substitui.',
 'Antes de tratar dislipidemia, afastar causa secundária: hipotireoidismo, diabetes descompensado, doença renal, hepatopatia e medicamentos são causas que a dieta não resolve. O cálculo de Friedewald perde validade com TG >400 — pedir LDL direto. Jejum não é mais obrigatório para o perfil lipídico de rotina (mas é para avaliar TG com precisão).'),

-- ══════════════ 7. OBESIDADE ══════════════
(null, 'Obesidade — manejo nutricional', 'obesidade',
 '{"emagrecimento","perda de peso","sobrepeso"}',
 'Condições clínicas', 'Obesidade',
 'Reduzir gordura corporal e risco cardiometabólico de forma sustentável, preservando massa magra e sem produzir dano psíquico no processo.',
 'O déficit energético é o que produz perda de peso — mas a escolha do padrão alimentar deve ser guiada pelo que a paciente sustenta, porque adesão prediz resultado melhor que composição de macronutrientes. Ensaios que compararam low carb com low fat (DIETFITS, entre outros) mostraram diferença clinicamente irrelevante entre padrões: o que separa quem mantém de quem recupera não é a dieta, é a sustentabilidade. Estruturar: déficit moderado (500–750 kcal/dia); proteína elevada (1,2–1,6 g/kg) para saciedade e preservação de massa magra; fibras 25–30 g/dia; reduzir ultraprocessados — no ensaio controlado de Hall et al., pessoas comeram cerca de 500 kcal/dia a mais em dieta ultraprocessada com macros equiparados, sem perceber. Treino de força é inegociável: sem ele, parcela relevante do peso perdido é massa magra, o que reduz o gasto e prepara o reganho. Manejar expectativa: perda de 5–10% já traz benefício metabólico documentado, e comunicar isso combate a frustração de não chegar ao "peso dos sonhos". Reganho é fisiologia (adaptação metabólica e hormonal), não fracasso moral — e tratar como fracasso moral é o que empurra a paciente para o ciclo de restrição e compulsão.',
 '[{"nutriente":"Proteína","papel":"Saciedade, efeito térmico e preservação de massa magra no déficit","dose":"1,2–1,6 g/kg/dia"},
   {"nutriente":"Fibras","papel":"Saciedade e qualidade da dieta","dose":"25–30 g/dia"},
   {"nutriente":"Ultraprocessados","papel":"Promovem ingestão excessiva mesmo com macros equiparados","dose":"Reduzir — alavanca subestimada"},
   {"nutriente":"Água","papel":"Substituir calorias líquidas","dose":"Eliminar bebidas açucaradas"},
   {"nutriente":"Vitamina D","papel":"Deficiência é comum (sequestro no tecido adiposo)","dose":"Corrigir; a necessidade costuma ser maior"}]',
 '{"homa-ir","insulina-jejum","glicemia-jejum","hba1c","tgp-alt","triglicerideos","hdl","ldl","tsh","vitamina-d","pcr-us","acido-urico"}',
 '{"Gordura visceral","Acantose nigricans","Sonolência diurna e ronco (rastrear apneia)","Dor articular","Dispneia aos esforços","Esteatose associada","Sofrimento psíquico e histórico de dietas restritivas"}',
 '[{"titulo":"5% já vale muito","tipo":"orientacao","detalhe":"Perda de 5–10% traz benefício metabólico documentado — manejar expectativa combate a frustração"},
   {"titulo":"Treino de força não é opcional","tipo":"habito","detalhe":"Sem ele, parte do peso perdido é músculo — o que reduz o gasto e prepara o reganho"},
   {"titulo":"Reganho é fisiologia, não fracasso","tipo":"orientacao","detalhe":"Adaptação metabólica e hormonal; tratar como falha moral alimenta o ciclo restrição-compulsão"}]',
 '[{"fonte":"Gardner CD et al. (DIETFITS)","ano":2018,"detalhe":"Effect of Low-Fat vs Low-Carbohydrate Diet on 12-Month Weight Loss. JAMA"},
   {"fonte":"Hall KD et al.","ano":2019,"detalhe":"Ultra-Processed Diets Cause Excess Calorie Intake and Weight Gain. Cell Metabolism"},
   {"fonte":"Associação Brasileira para o Estudo da Obesidade (ABESO)","ano":2016,"detalhe":"Diretrizes Brasileiras de Obesidade"},
   {"fonte":"Sumithran P et al.","ano":2011,"detalhe":"Long-term persistence of hormonal adaptations to weight loss. New England Journal of Medicine"}]',
 'Rastrear apneia do sono (ronco, sonolência diurna) — é subdiagnosticada e sabota o emagrecimento. Transtorno alimentar (compulsão, purgação, restrição severa) exige equipe com psicólogo e psiquiatra. Indicação de farmacoterapia ou cirurgia bariátrica é médica. IMC ≥40, ou ≥35 com comorbidade: avaliar encaminhamento.',
 'Cuidado com o dano da própria intervenção: prescrever restrição agressiva a quem já tem histórico de dietas e compulsão pode piorar o quadro alimentar e o sofrimento. Peso não é o único desfecho — composição corporal, exames, sono e relação com a comida contam. Rastrear transtorno alimentar ANTES de prescrever restrição.'),

-- ══════════════ 8. CONSTIPAÇÃO ══════════════
(null, 'Constipação intestinal', 'constipacao',
 '{"intestino preso","prisão de ventre","obstipação"}',
 'Sistemas', 'Digestório',
 'Restabelecer o ritmo intestinal com fibra, água e movimento, reduzindo a dependência de laxante.',
 'Ordem importa aqui, e errar a ordem é o que faz o tratamento falhar: aumentar fibra SEM aumentar água piora a constipação. Estruturar: hidratação primeiro (30–35 mL/kg/dia); fibra progressiva até 25–30 g/dia — aumento gradual para evitar distensão e gases, que é a causa mais comum de abandono; priorizar fibra solúvel e formadora de bolo (psyllium tem a melhor evidência entre os suplementos de fibra); kiwi, ameixa e mamão têm respaldo; atividade física; e reeducar o reflexo gastrocólico — sentar no vaso após o café da manhã, sem pressa e sem celular, aproveitando a janela fisiológica. Não suprimir a vontade. Revisar medicamentos: opioides, antidepressivos tricíclicos, ferro, cálcio, anti-hipertensivos e antiácidos com alumínio constipam, e o paciente raramente faz essa conexão sozinho.',
 '[{"nutriente":"Água","papel":"Sem hidratação, aumentar fibra PIORA a constipação — a ordem importa","dose":"30–35 mL/kg/dia"},
   {"nutriente":"Fibras","papel":"Formação e amolecimento do bolo fecal","dose":"25–30 g/dia, aumento gradual"},
   {"nutriente":"Psyllium","papel":"Melhor evidência entre os suplementos de fibra","dose":"Iniciar baixo e progredir, sempre com água"},
   {"nutriente":"Kiwi e ameixa","papel":"Efeito laxativo com respaldo em ensaios","dose":"2 kiwis/dia ou ameixas"},
   {"nutriente":"Magnésio","papel":"O óxido tem efeito osmótico laxativo","dose":"Uso pontual; avaliar função renal antes"}]',
 '{"tsh","calcio","magnesio","hemoglobina","ferritina"}',
 '{"Menos de 3 evacuações por semana","Fezes endurecidas ou fragmentadas (Bristol 1–2)","Esforço evacuatório","Sensação de evacuação incompleta","Distensão abdominal","Dor ao evacuar"}',
 '[{"titulo":"Fibra sem água é armadilha","tipo":"orientacao","detalhe":"Aumentar fibra sem hidratação piora — hidratar primeiro, fibra depois"},
   {"titulo":"A janela do reflexo gastrocólico","tipo":"habito","detalhe":"Sentar no vaso após o café da manhã, com calma; não suprimir a vontade"},
   {"titulo":"Escala de Bristol","tipo":"orientacao","detalhe":"Ferramenta simples para a paciente relatar sem constrangimento"}]',
 '[{"fonte":"American Gastroenterological Association (AGA/ACG)","ano":2023,"detalhe":"Clinical Practice Guideline: Pharmacological Management of Chronic Idiopathic Constipation"},
   {"fonte":"Bharucha AE, Lacy BE.","ano":2020,"detalhe":"Mechanisms, Evaluation, and Management of Chronic Constipation. Gastroenterology"},
   {"fonte":"Christodoulides S et al.","ano":2016,"detalhe":"Systematic review with meta-analysis: effect of fibre supplementation on chronic idiopathic constipation. Alimentary Pharmacology and Therapeutics"}]',
 'Sinais de alarme exigem encaminhamento e não podem ser tratados como constipação funcional: sangue nas fezes, perda de peso inexplicada, anemia, mudança recente e persistente do hábito intestinal após os 50 anos, história familiar de câncer colorretal, massa abdominal palpável, constipação refratária.',
 'Investigar hipotireoidismo, hipercalcemia e medicamentos antes de assumir causa alimentar — são causas comuns e a dieta não resolve nenhuma delas. Aumento rápido de fibra causa distensão e gases, e é a razão mais frequente de a paciente abandonar. Uso crônico de laxante estimulante merece atenção e desmame planejado.'),

-- ══════════════ 9. REFLUXO / DRGE ══════════════
(null, 'Refluxo gastroesofágico (DRGE)', 'refluxo-drge',
 '{"refluxo","DRGE","azia","queimação","pirose"}',
 'Sistemas', 'Digestório',
 'Reduzir sintomas e episódios de refluxo com medidas alimentares e comportamentais de evidência real, evitando restrições inúteis.',
 'Aqui é importante separar o que funciona do que é tradição. As medidas com MELHOR evidência não são alimentares: perda de peso (mesmo modesta, reduz sintomas de forma consistente), elevar a cabeceira 15–20 cm com calço — não travesseiro, que dobra o corpo e piora —, e não deitar nas 3 horas após comer. Sobre alimentos, a evidência é mais fraca do que a prática sugere: as diretrizes recomendam restrição INDIVIDUALIZADA pelos gatilhos que a própria paciente identifica, não uma lista proibida universal. Proibir café, chocolate, tomate e cítricos de todo mundo empobrece a dieta sem ganho comprovado, e mina a confiança quando a paciente descobre que tolera. Estruturar: refeições menores e mais frequentes; evitar volume grande à noite; identificar gatilhos individuais com diário alimentar; reduzir álcool e tabagismo (esses sim têm respaldo).',
 '[{"nutriente":"Peso corporal","papel":"Perda de peso é a medida alimentar com melhor evidência","dose":"Mesmo redução modesta reduz sintomas"},
   {"nutriente":"Volume das refeições","papel":"Refeições volumosas aumentam relaxamento transitório do esfíncter","dose":"Menores e mais frequentes"},
   {"nutriente":"Álcool","papel":"Reduz o tônus do esfíncter esofágico inferior","dose":"Restringir"},
   {"nutriente":"Gatilhos individuais","papel":"A evidência apoia restrição individualizada, não lista universal","dose":"Identificar com diário alimentar"}]',
 '{"hemoglobina","ferritina","vitamina-b12","magnesio"}',
 '{"Pirose (queimação retroesternal)","Regurgitação","Tosse crônica noturna","Rouquidão matinal","Sensação de globus","Dor torácica não cardíaca","Erosão dentária"}',
 '[{"titulo":"Calço, não travesseiro","tipo":"habito","detalhe":"Elevar a cabeceira 15–20 cm com calço; travesseiro dobra o corpo e piora"},
   {"titulo":"Três horas antes de deitar","tipo":"habito","detalhe":"Última refeição com antecedência — das medidas mais eficazes"},
   {"titulo":"Descubra SEU gatilho","tipo":"orientacao","detalhe":"Diário alimentar; a lista universal de proibições não tem respaldo"}]',
 '[{"fonte":"American College of Gastroenterology","ano":2022,"detalhe":"ACG Clinical Guideline for the Diagnosis and Management of Gastroesophageal Reflux Disease"},
   {"fonte":"Ness-Jensen E et al.","ano":2016,"detalhe":"Lifestyle Intervention in Gastroesophageal Reflux Disease. Clinical Gastroenterology and Hepatology"},
   {"fonte":"Katz PO et al.","ano":2022,"detalhe":"Guidelines for the Diagnosis and Management of Gastroesophageal Reflux Disease. American Journal of Gastroenterology"}]',
 'Sinais de alarme pedem endoscopia e encaminhamento: disfagia, odinofagia, perda de peso, anemia, vômito persistente, sangramento, história familiar de câncer gástrico ou esofágico, sintomas refratários, início após os 60 anos.',
 'Uso crônico de inibidor de bomba de prótons (IBP) associa-se a má absorção de B12, magnésio, ferro e cálcio — em paciente com IBP de longa data, dosar esses nutrientes. Suspensão ou ajuste de IBP é decisão médica, e a retirada abrupta causa hipersecreção rebote. A lista universal de alimentos proibidos tem menos respaldo do que se pratica.'),

-- ══════════════ 10. DEFICIÊNCIA DE VITAMINA D ══════════════
(null, 'Deficiência de vitamina D', 'deficiencia-vitamina-d',
 '{"vitamina D baixa","hipovitaminose D"}',
 'Bioquímica e exames', 'Vitaminas',
 'Corrigir a deficiência com segurança, priorizando saúde óssea e muscular, sem prometer o que a evidência não sustenta.',
 'Estruturar: exposição solar regular como base; suplementação conforme a magnitude do déficit e o grupo de risco; ingerir com refeição que contenha gordura (é lipossolúvel); garantir magnésio adequado — sem magnésio a ativação enzimática é prejudicada e a resposta à suplementação fica ruim; garantir cálcio adequado, já que repor vitamina D sem cálcio limita o efeito ósseo. Reavaliar em 8–12 semanas, não antes: o platô ainda não foi atingido e o exame não informa. Uma honestidade necessária na conversa com a paciente: a evidência é sólida para osso e função muscular (queda e fratura no idoso); para desfechos extraósseos — câncer, doença cardiovascular, prevenção de diabetes — os grandes ensaios randomizados (VITAL, D-Health) NÃO mostraram benefício da suplementação em quem não tem deficiência. Corrigir deficiência é indicado; suplementar quem já está suficiente esperando benefício geral não é.',
 '[{"nutriente":"Vitamina D","papel":"Reposição","dose":"Conforme déficit e grupo de risco; dose diária ou semanal é mais segura que megadose"},
   {"nutriente":"Magnésio","papel":"Cofator das enzimas de ativação; deficiência associa-se a resposta ruim","dose":"Garantir adequação antes de culpar a dose"},
   {"nutriente":"Cálcio","papel":"Repor D sem cálcio adequado limita o efeito ósseo","dose":"Garantir ingestão"},
   {"nutriente":"Gordura alimentar","papel":"Necessária à absorção","dose":"Tomar junto com refeição"},
   {"nutriente":"Vitamina K2","papel":"Direciona o cálcio ao osso — plausível, evidência de desfecho limitada","dose":"Não é rotina"}]',
 '{"vitamina-d","calcio","pth","magnesio","fosfatase-alcalina"}',
 '{"Dor óssea difusa","Fraqueza muscular proximal (dificuldade de levantar da cadeira, subir escada)","Quedas de repetição no idoso","Infecções respiratórias de repetição","Humor deprimido","Frequentemente assintomática"}',
 '[{"titulo":"Sol com bom senso","tipo":"habito","detalhe":"Exposição regular de braços e pernas, sem buscar queimadura; a base é solar"},
   {"titulo":"Tome junto com gordura","tipo":"orientacao","detalhe":"É lipossolúvel — em jejum absorve mal"},
   {"titulo":"Reavaliar só em 8–12 semanas","tipo":"orientacao","detalhe":"Antes disso o exame não reflete o efeito"}]',
 '[{"fonte":"Endocrine Society","ano":2011,"detalhe":"Evaluation, Treatment, and Prevention of Vitamin D Deficiency: Clinical Practice Guideline"},
   {"fonte":"Institute of Medicine (IOM/NASEM)","ano":2011,"detalhe":"Dietary Reference Intakes for Calcium and Vitamin D"},
   {"fonte":"SBEM / SBPC-ML","ano":2017,"detalhe":"Posicionamento oficial sobre intervalos de referência da vitamina D"},
   {"fonte":"Manson JE et al. (VITAL)","ano":2019,"detalhe":"Vitamin D Supplements and Prevention of Cancer and Cardiovascular Disease. New England Journal of Medicine"},
   {"fonte":"Sanders KM et al.","ano":2010,"detalhe":"Annual high-dose oral vitamin D and falls and fractures in older women. JAMA"}]',
 'Hipercalcemia, nefrolitíase de repetição, doença granulomatosa (sarcoidose, tuberculose) ou insuficiência renal: a suplementação precisa de acompanhamento médico. Deficiência que não corrige com dose adequada levanta má absorção — investigar celíaca, doença inflamatória intestinal e histórico de bariátrica.',
 'MEGADOSES intermitentes (300.000–600.000 UI) associaram-se a AUMENTO de quedas e fraturas em idosos em ensaios randomizados — dose diária ou semanal é mais segura. Não dosar 1,25-OH para avaliar status: ela se mantém normal ou sobe na deficiência e engana. Obesidade sequestra vitamina D no tecido adiposo, e a necessidade costuma ser maior. Não prometer benefício extraósseo: os grandes ensaios não sustentam.'),

-- ══════════════ 11. COMPULSÃO ALIMENTAR ══════════════
(null, 'Compulsão alimentar', 'compulsao-alimentar',
 '{"TCAP","comer compulsivo","binge","descontrole alimentar"}',
 'Transversais', 'Nutrição comportamental',
 'Reduzir episódios de compulsão e restabelecer uma relação funcional com a comida — sem que a intervenção nutricional alimente o ciclo.',
 'O ponto que muda tudo: restrição alimentar é fator PERPETUADOR da compulsão, não tratamento. Prescrever dieta restritiva para quem tem compulsão costuma piorar. O ciclo é restrição → fome e privação → compulsão → culpa → restrição mais severa, e a prescrição errada entra nele como combustível. Estruturar: regularizar refeições — comer de 3 em 3 horas reduz a fome extrema que dispara o episódio; garantir energia e proteína adequadas (não restringir); abandonar a linguagem de alimento "proibido", já que a proibição aumenta o desejo e a culpa pós-episódio; trabalhar comer com atenção plena; identificar gatilhos emocionais junto com a paciente. O tratamento com melhor evidência para transtorno de compulsão alimentar periódica é a TERAPIA COGNITIVO-COMPORTAMENTAL, e o cuidado é multiprofissional: o nutricionista é peça, não o todo. Reconhecer isso é parte do cuidado, não abdicação.',
 '[{"nutriente":"Regularidade das refeições","papel":"Reduz a fome extrema que dispara o episódio","dose":"Refeições a cada 3–4h, sem pular"},
   {"nutriente":"Proteína","papel":"Saciedade e estabilidade","dose":"Distribuída ao longo do dia"},
   {"nutriente":"Energia adequada","papel":"Déficit agressivo perpetua o ciclo","dose":"NÃO restringir durante a fase ativa"},
   {"nutriente":"Fibras","papel":"Saciedade","dose":"Adequação, sem radicalismo"}]',
 '{"hemoglobina","ferritina","vitamina-d","tsh","hba1c","vitamina-b12"}',
 '{"Episódios de ingestão em quantidade grande com sensação de perda de controle","Comer rápido e às escondidas","Comer sem fome física","Culpa e vergonha após o episódio","Histórico de dietas restritivas repetidas","Flutuação de peso","Humor deprimido e ansiedade associados"}',
 '[{"titulo":"Não existe alimento proibido","tipo":"orientacao","detalhe":"A proibição aumenta o desejo e a culpa — e a culpa alimenta o próximo episódio"},
   {"titulo":"Comer de 3 em 3 horas","tipo":"habito","detalhe":"Regularidade reduz a fome extrema que dispara a compulsão"},
   {"titulo":"O ciclo restrição-compulsão","tipo":"orientacao","detalhe":"Entender o ciclo é parte do tratamento: restrição → privação → compulsão → culpa → mais restrição"}]',
 '[{"fonte":"Hilbert A et al.","ano":2019,"detalhe":"Meta-analysis of the efficacy of psychological and medical treatments for binge-eating disorder. Journal of Consulting and Clinical Psychology"},
   {"fonte":"National Institute for Health and Care Excellence (NICE)","ano":2017,"detalhe":"Eating disorders: recognition and treatment (NG69)"},
   {"fonte":"American Psychiatric Association","ano":2023,"detalhe":"Practice Guideline for the Treatment of Patients with Eating Disorders"},
   {"fonte":"Alvarenga M, Figueiredo M, Timerman F, Antonaccio C.","ano":2015,"detalhe":"Nutrição Comportamental. Manole"}]',
 'Encaminhar para psicólogo e psiquiatra — o tratamento é multiprofissional e a TCC tem a melhor evidência. Sinais de purgação (vômito, laxante, diurético), restrição severa, ideação suicida, ou instabilidade clínica: encaminhamento prioritário. Nutricionista não conduz transtorno alimentar sozinho.',
 'Prescrever dieta restritiva aqui pode PIORAR o quadro — é o erro mais comum e mais custoso. Rastrear transtorno alimentar antes de qualquer prescrição de emagrecimento, inclusive em quem procura por outro motivo. Pesar a paciente pode ser gatilho: perguntar antes, e considerar pesagem de costas ou não pesar. O foco no peso pode ser parte do problema, não da solução.'),

-- ══════════════ 12. SARCOPENIA ══════════════
(null, 'Sarcopenia e envelhecimento', 'sarcopenia',
 '{"perda de massa muscular","sarcopenia","fragilidade","idoso"}',
 'Condições clínicas', 'Envelhecimento',
 'Preservar massa e força muscular, reduzir risco de queda e fratura e sustentar autonomia funcional.',
 'Dois pilares, e nenhum funciona sozinho: proteína adequada e treino de força. Proteína — a recomendação para o idoso é MAIOR que a do adulto jovem: 1,0–1,2 g/kg/dia para o idoso saudável e 1,2–1,5 g/kg/dia na presença de doença, porque há resistência anabólica (o músculo idoso responde menos ao mesmo estímulo). A RDA de 0,8 g/kg é insuficiente para essa população e seguir a RDA aqui é erro. Distribuir a proteína ao longo do dia (25–30 g por refeição) supera concentrar tudo no jantar, que é o padrão brasileiro comum — o café da manhã costuma ser o buraco. Leucina é o gatilho da síntese proteica. Treino de força é o estímulo insubstituível: sem ele a proteína sozinha não constrói músculo. Garantir vitamina D (função muscular e prevenção de queda) e energia total adequada — em déficit energético, a proteína vira combustível em vez de músculo. Atenção a barreiras práticas que são invisíveis na prescrição: dentição, disfagia, apetite reduzido, solidão nas refeições, dificuldade de cozinhar e limitação financeira.',
 '[{"nutriente":"Proteína","papel":"Substrato; há resistência anabólica no idoso — a RDA de 0,8 g/kg é insuficiente","dose":"1,0–1,2 g/kg/dia (saudável); 1,2–1,5 (doença)"},
   {"nutriente":"Leucina","papel":"Gatilho da síntese proteica muscular","dose":"~2,5–3 g por refeição (fontes de alto valor biológico)"},
   {"nutriente":"Vitamina D","papel":"Função muscular e prevenção de quedas","dose":"Corrigir deficiência"},
   {"nutriente":"Energia total","papel":"Em déficit, a proteína é oxidada em vez de virar músculo","dose":"Adequar antes de aumentar proteína"},
   {"nutriente":"Ômega-3","papel":"Possível atenuação da resistência anabólica; evidência ainda modesta","dose":"Caso a caso"},
   {"nutriente":"Creatina","papel":"Associada ao treino de força, melhora força e massa magra no idoso","dose":"3–5 g/dia; avaliar função renal antes"}]',
 '{"albumina","creatinina-tfg","vitamina-d","hemoglobina","vitamina-b12","tsh"}',
 '{"Perda de força de preensão","Lentidão da marcha","Dificuldade de levantar da cadeira sem apoio","Quedas","Perda de peso não intencional","Fadiga","Redução de circunferência de panturrilha"}',
 '[{"titulo":"Proteína no café da manhã","tipo":"orientacao","detalhe":"Distribuir 25–30 g por refeição supera concentrar no jantar — o café é o buraco mais comum"},
   {"titulo":"Treino de força depois dos 60","tipo":"habito","detalhe":"Estímulo insubstituível: sem ele, proteína sozinha não constrói músculo"},
   {"titulo":"O que atrapalha comer","tipo":"orientacao","detalhe":"Dentição, disfagia, apetite, solidão e dinheiro — barreiras invisíveis na prescrição"}]',
 '[{"fonte":"Cruz-Jentoft AJ et al. (EWGSOP2)","ano":2019,"detalhe":"Sarcopenia: revised European consensus on definition and diagnosis. Age and Ageing"},
   {"fonte":"Bauer J et al. (PROT-AGE)","ano":2013,"detalhe":"Evidence-based recommendations for optimal dietary protein intake in older people. Journal of the American Medical Directors Association"},
   {"fonte":"Deutz NE et al. (ESPEN)","ano":2014,"detalhe":"Protein intake and exercise for optimal muscle function with aging. Clinical Nutrition"},
   {"fonte":"Chilibeck PD et al.","ano":2017,"detalhe":"Effect of creatine supplementation during resistance training on lean tissue mass and muscular strength in older adults. Open Access Journal of Sports Medicine"}]',
 'Perda de peso não intencional, disfagia, quedas de repetição ou fragilidade estabelecida pedem avaliação médica e equipe multiprofissional (fisioterapia, fonoaudiologia). Investigar causas tratáveis de perda de peso no idoso — neoplasia, depressão, demência, polifarmácia — antes de assumir causa nutricional.',
 'A RDA de 0,8 g/kg/dia é insuficiente para o idoso — seguir a RDA aqui contribui para a sarcopenia. Restrição proteica na doença renal crônica precisa ser individualizada com o médico, e o risco de sarcopenia entra na conta. Albumina NÃO serve para avaliar estado nutricional (posição ASPEN): usar anamnese, antropometria, força de preensão e velocidade de marcha.')

on conflict (slug) where (nutricionista_id is null) do update set
  sinonimos = excluded.sinonimos,
  eixo = excluded.eixo,
  grupo = excluded.grupo,
  objetivo_clinico = excluded.objetivo_clinico,
  estrategia = excluded.estrategia,
  nutrientes = excluded.nutrientes,
  exames_slugs = excluded.exames_slugs,
  sinais_sintomas = excluded.sinais_sintomas,
  materiais_apoio = excluded.materiais_apoio,
  referencias = excluded.referencias,
  quando_encaminhar = excluded.quando_encaminhar,
  atencao = excluded.atencao,
  updated_at = now();

notify pgrst, 'reload schema';
